Added lefty support
flipperdevices/flipperzero-firmware pull request #1235
Opened 2022-05-15 23:15 UTC by MrDaGree

# What's new

- Added hand orientation setting in `Settings > System > Hand Orient` for #1015 and myself as a lefty user with this. When the option changes between lefty and righty it will then reboot the flipper to ensure the proper orientation of the screen

# Verification 

1. To verify the change you should be able to go to `Settings > System` and see an option called `Hand Orient`. 
2. From there you can change the orientation and after a reboot happens it will then flip the screen for left-handed users like myself. 
3. You can also go to `Infrared > Universal Library > TVs` to verify the vertical orientation and controls still function as they should

# Checklist (For Reviewer)

- [ ] PR has description of feature/bug or link to Confluence/Jira task
- [ ] Description contains actions to verify feature/bugfix
- [ ] I've built this code, uploaded it to the device and verified feature/bugfix

This is my first time contributing to here so please let me know if theres anything I should change!

2022-05-16 13:11 UTC, skotopes requested changes

2022-05-16 13:11 UTC, skotopes commented on applications/system/system_settings.c
> +    power_reboot(PowerBootModeNormal);
Reboot here looks like dirty hack.

The best option will be to add getter/setter API methods to GUI and handle orientation change in GUI module. Also loader_update_menu is meaningless here.

Aslo buttons rotation must be implemented in GUI module. You can leave it as is, I'll refactor input.

And please run `make format`

2022-05-23 20:58 UTC, skotopes commented
@MrDaGree do you want me to continue work or wanna try by your self?

2022-10-27 06:43 UTC, br0ziliy commented
@MrDaGree https://github.com/flipperdevices/flipperzero-firmware/pull/1928 adds screen orientation setting support in GUI, along with buttons rotation; you might want to rework this PR.

2022-10-29 19:59 UTC, closed without merging