Rework NFC EMV response parsing.  Split TLV and tags per EMV spec.
flipperdevices/flipperzero-firmware pull request #1257
Opened 2022-05-20 23:08 UTC by SnowLeopard71

# What's new

- replaced several functions with one to parse all EMV responses uniformly using a *switch-case*
- added trace output for transmitted data

# Verification 

- tested on 6 different bank cards and all work as expected with these changes.  2 do not work properly with current release.

# Checklist (For Reviewer)

- [ ] PR has description of feature/bug or link to Confluence/Jira task
- [ ] Description contains actions to verify feature/bugfix
- [ ] I've built this code, uploaded it to the device and verified feature/bugfix

2022-05-21 14:55 UTC, SnowLeopard71 commented
Sorry, I did not know to run *make lint* to check the formatting.   Fixed it and no errors/warnings anymore.

2022-05-23 16:17 UTC, gornekich requested changes
Thank you for the contribution, great work!
Please fix logging issue and we merge your PR

2022-05-23 16:17 UTC, gornekich commented on lib/nfc_protocols/emv.c
> +    uint16_t tag = 0, fb = 0;
Could you please name variables more clear. first_byte is much better, and you don't need to explain it in the comment below

2022-05-23 16:17 UTC, gornekich commented on lib/nfc_protocols/emv.c
> +                printf("Failed to decode response for %x \r\n", tag);
Change to FURI_LOG_T() please

2022-05-23 16:49 UTC, SnowLeopard71 commented
I made requested changes...  I'll need a better _git checklist_ so my _commits_ and _pushes_ are not such a mess next time.

2022-05-23 17:20 UTC, gornekich commented
@SnowLeopard71 please, format sources (make format)

2022-05-23 17:31 UTC, gornekich requested changes
It's totally fine, don't worry =)
I ask you to avoid commit messages that don't include unnecessary information as they go to Changelog. Just "fix build" or "format sources" is enough

2022-05-23 17:31 UTC, gornekich commented on lib/nfc_protocols/emv.c
> +                FURI_LOG_T(tag, "Failed to decode response for %x", tag);
Change to TAG. This breaks build

2022-05-23 17:41 UTC, gornekich approved these changes

2022-05-23 17:57 UTC, skotopes approved these changes

2022-05-23 17:58 UTC, merged