Fix typos in macOS Bad USB demo
flipperdevices/flipperzero-firmware pull request #1316
Opened 2022-06-13 19:38 UTC by ianegordon

# What's new

- Fix typos in the macOS Bad USB demo script

# Verification 

- Changes may be verified by running the demo_macos Bad USB script while the Flipper is plugged into a macOS machine.  Changes are trivial, but the script was successfully tested on an Apple M1 MacBook Pro running macOS Monterey 12.4.

# Checklist (For Reviewer)

- [x] PR has description of feature/bug or link to Confluence/Jira task
- [x] Description contains actions to verify feature/bugfix
- [x] I've built this code, uploaded it to the device and verified feature/bugfix

2022-06-13 20:33 UTC, hedger commented
Please don't tick the checkboxes, they are marked "for reviewer" for a reason.

2022-06-13 20:33 UTC, hedger approved these changes

2022-06-13 20:38 UTC, hedger commented
When updating SD card resources, you need to rebuild Manifest and commit it. 

Please run `make assets_manifest`.

2022-06-13 20:39 UTC, hedger requested changes
Assets manifest update is required

2022-06-13 22:16 UTC, hedger approved these changes

2022-06-14 00:56 UTC, skotopes approved these changes

2022-06-14 00:57 UTC, merged