Furi: core refactoring and CMSIS removal part 2
flipperdevices/flipperzero-firmware pull request #1410
Opened 2022-07-17 11:02 UTC by skotopes

# What's new

- Furi: core refactoring and CMSIS removal part 2 

# Verification 

- Compile and upload
- Do release and unit tests 

# Checklist (For Reviewer)

- [ ] PR has description of feature/bug or link to Confluence/Jira task
- [ ] Description contains actions to verify feature/bugfix
- [ ] I've built this code, uploaded it to the device and verified feature/bugfix

2022-07-18 16:51 UTC, DrZlo13 requested changes

2022-07-18 16:51 UTC, DrZlo13 commented on applications/dialogs/view_holder.c
> +    while(view_holder->ongoing_input) furi_delay_ms(1);
furi_delay_tick

2022-07-18 16:51 UTC, DrZlo13 commented on applications/input/input.c
> +            furi_delay_ms(1);
furi_delay_tick

2022-07-18 16:51 UTC, DrZlo13 commented on applications/music_player/music_player_worker.c
> +                furi_delay_ms(2);
furi_delay_tick

2022-07-18 16:51 UTC, DrZlo13 commented on firmware/targets/f7/ble_glue/ble_glue.c
> +            furi_delay_ms(1);
furi_delay_tick

2022-07-18 16:51 UTC, DrZlo13 commented on applications/unit_tests/rpc/rpc_test.c
> +        furi_delay_ms(1);
furi_delay_tick

2022-07-18 16:51 UTC, DrZlo13 commented on applications/unit_tests/rpc/rpc_test.c
> +        furi_delay_ms(1);
furi_delay_tick

2022-07-18 16:51 UTC, DrZlo13 commented on applications/subghz/views/receiver.c
> +        furi_timer_start(subghz_receiver->timer, pdMS_TO_TICKS(1000));
FURI_MS_TO_TICKS ?

2022-07-18 16:51 UTC, DrZlo13 commented on furi/furi.c
> +    CoreDebug->DEMCR |= CoreDebug_DEMCR_TRCENA_Msk;
Platform specific code in the core?

2022-07-18 16:51 UTC, DrZlo13 commented on lib/subghz/subghz_tx_rx_worker.c
> +        furi_delay_ms(1);
furi_delay_tick

2022-07-18 16:51 UTC, DrZlo13 commented on lib/subghz/subghz_tx_rx_worker.c
> +        furi_delay_ms(1);
furi_delay_tick

2022-07-18 16:51 UTC, DrZlo13 commented on lib/subghz/subghz_tx_rx_worker.c
> +        furi_delay_ms(1);
furi_delay_tick

2022-07-18 16:51 UTC, DrZlo13 commented on lib/subghz/subghz_tx_rx_worker.c
> +        furi_delay_ms(1);
furi_delay_tick

2022-07-18 16:51 UTC, DrZlo13 commented on lib/subghz/subghz_tx_rx_worker.c
> +        furi_delay_ms(1);
furi_delay_tick

2022-07-19 11:07 UTC, skotopes commented on applications/music_player/music_player_worker.c
> +                furi_delay_ms(2);
Was meant to be 2 ms delay

2022-07-19 11:16 UTC, hedger requested changes

2022-07-19 11:16 UTC, hedger commented on applications/desktop/animations/animation_manager.c
> +    furi_timer_start(animation_manager->idle_animation_timer, bubble_animation->duration * 1000);
furi_ms_to_ticks ?

2022-07-19 11:16 UTC, hedger commented on applications/desktop/animations/animation_manager.c
>                              animation_manager->idle_animation_timer, animation->duration * 1000);
furi_ms_to_ticks?

2022-07-19 11:16 UTC, hedger commented on applications/desktop/animations/animation_manager.c
>                              animation_manager->freezed_animation_time_left);
furi_ms_to_ticks?

2022-07-19 11:16 UTC, hedger commented on applications/gui/icon_animation.c
> +    while(xTimerIsTimerActive(instance->timer) == pdTRUE) furi_delay_ms(1);
make xTimerIsTimerActive private? + os_delay_ticks

2022-07-19 11:16 UTC, hedger commented on applications/gui/icon_animation.c
>              xTimerChangePeriod(
make xTimerChangePeriod private?

2022-07-19 11:16 UTC, hedger commented on applications/gui/modules/popup.c
> +        uint32_t timer_period =
furi_ms_to_ticks?

2022-07-19 11:16 UTC, hedger commented on applications/gui/modules/text_input.c
> +            furi_timer_start(text_input->timer, furi_kernel_get_tick_frequency() * 4);
furi_ms_to_ticks ?

2022-07-19 11:16 UTC, hedger commented on applications/input/input.c
>      furi_check(xTimerChangePeriod(hTimer, ticks, portMAX_DELAY) == pdPASS);
make xTimerChangePeriod private?

2022-07-19 11:16 UTC, hedger commented on applications/input/input.c
> +    while(xTimerIsTimerActive(hTimer) == pdTRUE) furi_delay_ms(1);
furi_delay_ticks + make xTimerIsTimerActive private?

2022-07-19 11:16 UTC, hedger commented on applications/lfrfid/helpers/rfid_reader.cpp
> +    const uint32_t seconds_to_switch = furi_kernel_get_tick_frequency() * 2.0f;
use ticks/ms coverter? @DrZlo13

2022-07-19 11:16 UTC, hedger commented on applications/music_player/music_player_worker.c
> +            furi_delay_ms(10);
_delay_ticks?

2022-07-19 11:16 UTC, hedger commented on applications/nfc/helpers/nfc_debug_pcap.c
> +    xStreamBufferSend(instance->stream, data, len, FuriWaitForever);
xStreamBufferSend

2022-07-19 11:16 UTC, hedger commented on applications/nfc/nfc_worker.c
> +                furi_delay_ms(1);
delay_ticks

2022-07-19 11:16 UTC, hedger commented on applications/snake_game/snake_game.c
> +    furi_timer_start(timer, furi_kernel_get_tick_frequency() / 4);
use ticks/ms conversion

2022-07-19 11:16 UTC, hedger commented on applications/subghz/helpers/subghz_frequency_analyzer_worker.c
> +        furi_delay_ms(10);
delay_ticks + fix delay

2022-07-19 11:16 UTC, hedger commented on applications/subghz/helpers/subghz_frequency_analyzer_worker.c
> +                furi_delay_ms(3);
delay_ticks + fix delay

2022-07-19 11:16 UTC, hedger commented on applications/subghz/helpers/subghz_frequency_analyzer_worker.c
> +                    furi_delay_ms(3);
delay_ticks + fix delay

2022-07-19 11:16 UTC, hedger commented on applications/subghz/views/receiver.c
> +            furi_timer_start(subghz_receiver->timer, pdMS_TO_TICKS(1000));
use furi ms/ticks conversion

2022-07-19 11:16 UTC, hedger commented on applications/subghz/views/receiver.c
> +            furi_timer_start(subghz_receiver->timer, pdMS_TO_TICKS(650));
use furi ms/ticks conversion

2022-07-19 11:16 UTC, hedger commented on applications/subghz/views/subghz_test_carrier.c
> +    furi_timer_start(subghz_test_carrier->timer, furi_kernel_get_tick_frequency() / 4);
use ms/ticks conversion?

2022-07-19 11:16 UTC, hedger commented on applications/subghz/views/subghz_test_packet.c
> +    furi_timer_start(instance->timer, furi_kernel_get_tick_frequency() / 4);
use ms/tick conversion?

2022-07-19 11:16 UTC, hedger commented on furi/core/semaphore.h
> + * @return     { description_of_the_return_value }
?

2022-07-19 11:16 UTC, hedger commented on furi/core/event_flag.h
> + * @return     { description_of_the_return_value }
fill in

2022-07-19 11:16 UTC, hedger commented on furi/core/event_flag.h
> + * @return     { description_of_the_return_value }
same

2022-07-19 11:16 UTC, hedger commented on furi/core/event_flag.h
> + * @return     { description_of_the_return_value }
+ rest in this file

2022-07-19 11:16 UTC, hedger commented on furi/core/kernel.h
> + * @return     { description_of_the_return_value }
fill in

2022-07-19 14:53 UTC, skotopes commented on applications/gui/modules/text_input.c
> +            furi_timer_start(text_input->timer, furi_kernel_get_tick_frequency() * 4);
in part 3

2022-07-19 14:53 UTC, skotopes commented on applications/input/input.c
>      furi_check(xTimerChangePeriod(hTimer, ticks, portMAX_DELAY) == pdPASS);
in part 3

2022-07-19 14:56 UTC, skotopes commented on applications/lfrfid/helpers/rfid_reader.cpp
> +    const uint32_t seconds_to_switch = furi_kernel_get_tick_frequency() * 2.0f;
Question for @DrZlo13

2022-07-19 14:56 UTC, skotopes commented on applications/music_player/music_player_worker.c
> +            furi_delay_ms(10);
nope, ms

2022-07-19 14:57 UTC, skotopes commented on applications/nfc/helpers/nfc_debug_pcap.c
> +    xStreamBufferSend(instance->stream, data, len, FuriWaitForever);
in part 3

2022-07-19 14:57 UTC, skotopes commented on applications/snake_game/snake_game.c
> +    furi_timer_start(timer, furi_kernel_get_tick_frequency() / 4);
in part 3

2022-07-19 14:59 UTC, skotopes commented on applications/subghz/helpers/subghz_frequency_analyzer_worker.c
> +        furi_delay_ms(10);
ms is ok here

2022-07-19 14:59 UTC, skotopes commented on applications/subghz/helpers/subghz_frequency_analyzer_worker.c
> +                furi_delay_ms(3);
nope ms here is intentional

2022-07-19 14:59 UTC, skotopes commented on applications/subghz/helpers/subghz_frequency_analyzer_worker.c
> +                    furi_delay_ms(3);
same

2022-07-19 14:59 UTC, skotopes commented on applications/subghz/views/receiver.c
> +            furi_timer_start(subghz_receiver->timer, pdMS_TO_TICKS(1000));
in part 3

2022-07-19 15:00 UTC, skotopes commented on applications/subghz/views/receiver.c
> +            furi_timer_start(subghz_receiver->timer, pdMS_TO_TICKS(650));
in part 3

2022-07-19 15:00 UTC, skotopes commented on applications/subghz/views/subghz_test_carrier.c
> +    furi_timer_start(subghz_test_carrier->timer, furi_kernel_get_tick_frequency() / 4);
in part 3

2022-07-19 15:00 UTC, skotopes commented on applications/subghz/views/subghz_test_packet.c
> +    furi_timer_start(instance->timer, furi_kernel_get_tick_frequency() / 4);
in part 3

2022-07-19 15:04 UTC, skotopes commented on applications/desktop/animations/animation_manager.c
> +    furi_timer_start(animation_manager->idle_animation_timer, bubble_animation->duration * 1000);
In part 3

2022-07-19 15:04 UTC, skotopes commented on applications/desktop/animations/animation_manager.c
>                              animation_manager->idle_animation_timer, animation->duration * 1000);
In part 3

2022-07-19 15:04 UTC, skotopes commented on applications/desktop/animations/animation_manager.c
>                              animation_manager->freezed_animation_time_left);
In part 3

2022-07-19 15:05 UTC, skotopes commented on applications/gui/modules/popup.c
> +        uint32_t timer_period =
In part 3

2022-07-19 15:16 UTC, DrZlo13 approved these changes

2022-07-19 15:18 UTC, DrZlo13 commented
200000 files are changed, with a million more well on the way

2022-07-20 10:55 UTC, hedger approved these changes

2022-07-20 10:56 UTC, merged