enable sparseCheckout, moving github actions from docker to raw shell
flipperdevices/flipperzero-firmware pull request #1412
Opened 2022-07-18 13:27 UTC by drunkbatya

# What's new

- [ Describe changes here ]

# Verification 

- [ Describe how to verify changes ]

# Checklist (For Reviewer)

- [ ] PR has description of feature/bug or link to Confluence/Jira task
- [ ] Description contains actions to verify feature/bugfix
- [ ] I've built this code, uploaded it to the device and verified feature/bugfix

2022-07-29 17:43 UTC, hedger requested changes

2022-07-29 17:43 UTC, hedger commented on site_scons/_black_version.py
> +version = "22.6.0"
no longer needed

2022-07-29 17:43 UTC, hedger commented on site_scons/site_init.py
> +sys.path.insert(0, os.path.join(os.getcwd(), "lib/black/src"))
no longer needed

2022-07-29 17:43 UTC, hedger commented on scripts/toolchain/fbtenv.sh
> +    echo "Warning! Not recomended to run this script mannualy! Use ./fbt !";
typo: manually

2022-07-29 17:43 UTC, hedger commented on scripts/lint_py.py
> +#!/usr/bin/env python3
whole file: no longer needed

2022-07-29 17:43 UTC, hedger commented on scripts/toolchain/fbtenv.sh
> +    printf '\tFBT_TOOLCHAIN_VERSION=10 SCRIPT_PATH=$(pwd) FBT_TOOLCHAIN_PATH=/tmp/ source scripts/toolchain/fbtenv.sh\n'
can we have a simpler way to run fbtenv? use defaults when sourcing from repo root?

2022-07-31 14:24 UTC, hedger approved these changes

2022-07-31 14:34 UTC, hedger requested changes

2022-07-31 14:34 UTC, hedger commented on .github/workflows/check_submodules.yml
> -name: 'Check submodules'
This check is still needed

2022-07-31 14:34 UTC, hedger commented on scripts/toolchain/fbtenv.sh
> +        echo "Please source this script being into flipperzero-firmware root directory, or specify 'SCRIPT_PATH' manualy";
>manualy 
typo

2022-08-01 13:48 UTC, aprosvetova commented on scripts/toolchain/fbtenv.sh
> -    echo "Running this script manually is wrong, please source it";
this was correct

2022-08-01 13:56 UTC, drunkbatya commented on scripts/toolchain/fbtenv.sh
> -    echo "Running this script manually is wrong, please source it";
Thanks, fixed

2022-08-01 15:15 UTC, hedger approved these changes, later dismissed

2022-08-02 13:54 UTC, hedger approved these changes

2022-08-02 14:03 UTC, skotopes approved these changes

2022-08-02 14:05 UTC, merged