Make printf great again
flipperdevices/flipperzero-firmware pull request #1438
Opened 2022-07-24 01:42 UTC by DrZlo13

# What's new

- [ Describe changes here ]

# Verification 

- [ Describe how to verify changes ]

# Checklist (For Reviewer)

- [ ] PR has description of feature/bug or link to Confluence/Jira task
- [ ] Description contains actions to verify feature/bugfix
- [ ] I've built this code, uploaded it to the device and verified feature/bugfix

2022-07-28 11:17 UTC, hedger requested changes

2022-07-28 11:17 UTC, hedger commented on applications/desktop/views/desktop_view_debug.c
> +        snprintf(buffer, 64, "%ld", (uint32_t)m->timestamp);
#define or sizeof pls

2022-07-28 11:17 UTC, hedger commented on applications/rpc/rpc_storage.c
> +            md5sum += snprintf(md5sum, 33, "%02x", hash[i]);
use md5sum_size

2022-07-28 11:17 UTC, hedger commented on applications/subghz/scenes/subghz_scene_receiver_config.c
> +            10,
sizeof()

2022-07-28 11:17 UTC, hedger commented on applications/subghz/scenes/subghz_scene_receiver_config.c
> +            10,
sizeof()

2022-07-28 11:17 UTC, hedger commented on applications/subghz/scenes/subghz_scene_receiver_config.c
> +        10,
sizeof()

2022-07-29 04:53 UTC, hedger approved these changes

2022-08-03 15:56 UTC, skotopes approved these changes

2022-08-03 16:00 UTC, merged