U2F over NFC
flipperdevices/flipperzero-firmware pull request #1510
Opened 2022-07-31 23:27 UTC by RvanBaarle

# What's new

- The ability to use U2F via NFC, instead of just over USB
- A load of magic numbers, and some other issues (which I'll fix before I remove the draft status)

# Verification 

- [ Describe how to verify changes ]

# Checklist (For Reviewer)

- [ ] PR has description of feature/bug or link to Confluence/Jira task
- [ ] Description contains actions to verify feature/bugfix
- [ ] I've built this code, uploaded it to the device and verified feature/bugfix

2022-08-13 09:50 UTC, miili requested changes
Awesome, learned something reading this implementation draft. Thanks for your workd!

2022-08-13 09:50 UTC, miili commented on applications/u2f/u2f_nfc.c
> +    if(buff_rx_len >= 24) {
Reverse logic here. Test for `buff_rx_len < 24`, eliminate a logical block.

2022-08-13 09:50 UTC, miili commented on applications/u2f/u2f_nfc.c
> +            if(memcmp(&buff_rx[3], "\x04\x00\x08\xa0\x00\x00\x06\x47\x2f\x00\x01", 11) != 0) {
Can you please add more insights what the byte sequences mean? Datasheets, documentation or comments.

2023-11-15 09:40 UTC, gornekich commented
Hello everyone!
Recently we released new NFC stack in https://github.com/flipperdevices/flipperzero-firmware/pull/3050 . Unfortunately, previous NFC API was not good enough to add new features like NFC over U2F. Now we finished working on new API and it is possible to make NFC over U2F application.

Thanks @RvanBaarle  for PR! I will close it for now, since we are not planning to support NFC over U2F in our firmware. However, if you want to continue working on it, you can write application and submit it to https://github.com/flipperdevices/flipper-application-catalog repository. If you have any questions, feel free to contact me on Discord.

2023-11-15 09:40 UTC, closed without merging

2023-11-15 21:41 UTC, ChristianTacke commented
Well, if the core "U2F over USB" application is part of the main flipper OS (like it currently is), then really that same application should also handle the U2F over NFC.

* It should use the same keys for both protocols. Or can an external U2F-over-NFC app use the same keys again in a proper in supported way?
* Sharing the U2F code would be really nice too. Same question: Could an external U2F-over-NFC app reuse code?