NFC: Edit UID feature
flipperdevices/flipperzero-firmware pull request #1513
Opened 2022-08-01 15:10 UTC by fork-bombed

# What's new

- Added an "Edit UID" option for saved NFC cards where only the UID can be emulated

# Verification 

- Check a saved NFC file where only the UID can be emulated, and a new option named "Edit UID" will appear
- The edit UID option will take you to the SetUid scene where you can change the hex value
- The UID will be automatically updated if you hit save, or the changes will be discared if you hit back

<img src="https://user-images.githubusercontent.com/57873842/182177494-285bd96c-f834-4ed4-8769-9ae944c69eca.png" width="300">

# Checklist (For Reviewer)

- [ ] PR has description of feature/bug or link to Confluence/Jira task
- [ ] Description contains actions to verify feature/bugfix
- [ ] I've built this code, uploaded it to the device and verified feature/bugfix

2022-08-01 17:15 UTC, gornekich commented
Hello @fork-bombed 
Why do you need to edit UID? Why can't you generate manually a new card?

2022-08-01 18:18 UTC, fork-bombed commented
> Hello @fork-bombed Why do you need to edit UID? Why can't you generate manually a new card?

Hi @gornekich. I actually came across the need for this today when testing a printer at work. The printer only checked the UID and I kept needing to create a new card manually, remember the previous bytes, and delete the old card to test different combinations. Given that only the UID can be emulated at this point, it makes sense that there should be a quick and easy way to edit the data.

2022-08-01 19:03 UTC, gornekich requested changes
I see. The main concern here is that you can't change UID for Mf Classic and Ultralight/NTAG tags, since there will be inconsistent UID on anticollision level and data inside these cards. I suggest to add Edit UID option only for cards, which data we can't read, except anticollision Info

2022-08-01 19:03 UTC, gornekich commented on applications/nfc/scenes/nfc_scene_saved_menu.c
> +        submenu_add_item(
Add check here
if (nfc->dev->dev_data.protocol == NfcDeviceProtocolUnknown)

2022-08-01 20:15 UTC, fork-bombed commented on applications/nfc/scenes/nfc_scene_saved_menu.c
> +        submenu_add_item(
Added.

2022-08-02 10:27 UTC, gornekich approved these changes
Great work, thanks!
Will be merged this week after 0.63 release

2022-08-03 16:57 UTC, skotopes approved these changes

2022-08-03 17:00 UTC, merged