SD info: Add dynamic units and free %
flipperdevices/flipperzero-firmware pull request #1634
Opened 2022-08-22 02:14 UTC by non-bin

# What's new

- Add dynamic storage units for free/total in settings->sd info
- Add free %

# Verification 

- Built and tested (64GB SD)

# Checklist (For Reviewer)

- [ ] PR has description of feature/bug or link to Confluence/Jira task
- [ ] Description contains actions to verify feature/bugfix
- [ ] I've built this code, uploaded it to the device and verified feature/bugfix

2022-08-22 17:47 UTC, skotopes requested changes

2022-08-22 17:47 UTC, skotopes commented on applications/storage_settings/scenes/storage_settings_scene_sd_info.c
> +        char unit_kb[] = "KB";
No need to put it in ram, use const.

2022-08-22 17:47 UTC, skotopes commented on applications/storage_settings/scenes/storage_settings_scene_sd_info.c
> +        double sd_total_val = (double)sd_info.kb_total;
Using float point math here is kinda overkill.

2022-08-22 17:47 UTC, skotopes commented on applications/storage_settings/scenes/storage_settings_scene_sd_info.c
> +        if(sd_total_val > 1024) {
Better solution will be to implement formatting function that takes double* and const char**

2022-08-22 17:47 UTC, skotopes commented on applications/storage_settings/scenes/storage_settings_scene_sd_info.c
> +        double sd_total_val = (double)sd_info.kb_total;
Especially using double. Float should be more than enough, use cast at the last moment when passing it to string_printf.

2022-08-27 07:42 UTC, skotopes commented
@non-bin do you plan to continue work on this PR?

2022-08-27 21:46 UTC, non-bin commented
Yeah I will

2022-10-08 18:10 UTC, closed without merging

2022-10-08 18:10 UTC, skotopes commented
Feel free to reopen when it will be ready