[FL-2800] Fix Mifare Classic 4K reading of the last 8 sectors
flipperdevices/flipperzero-firmware pull request #1712
Opened 2022-09-06 17:59 UTC by Astrrra

# What's new

- When reading a MFC4K card, the sectors 32-40 should be read correctly now

# Verification 

- Read a Mifare Classic 4K card, verify the dump contents.

# Checklist (For Reviewer)

- [x] PR has description of feature/bug or link to Confluence/Jira task
- [x] Description contains actions to verify feature/bugfix
- [x] I've built this code, uploaded it to the device and verified feature/bugfix

2022-09-06 18:32 UTC, gornekich requested changes

2022-09-06 18:32 UTC, gornekich commented on lib/nfc/protocols/mifare_classic.c
> +        FURI_BIT_SET(data->key_a_mask, (uint64_t)sector_num);
don't need it here

2022-09-06 18:35 UTC, Astrrra commented on lib/nfc/protocols/mifare_classic.c
> +        FURI_BIT_SET(data->key_a_mask, (uint64_t)sector_num);
Oh, right

2022-09-13 09:34 UTC, gornekich submitted a review, later dismissed

2022-09-15 16:00 UTC, skotopes approved these changes

2022-09-19 12:25 UTC, skotopes approved these changes

2022-09-19 12:30 UTC, merged