add Hisense A/C IR signals..
flipperdevices/flipperzero-firmware pull request #1773
Opened 2022-09-23 21:07 UTC by phreakocious

# What's new

- Hisense A/C controls

# Verification 

- Point at Hisense A/C and play

# Checklist (For Reviewer)

- [ ] PR has description of feature/bug or link to Confluence/Jira task
- [ ] Description contains actions to verify feature/bugfix
- [ ] I've built this code, uploaded it to the device and verified feature/bugfix

2022-09-24 14:56 UTC, ioload commented
Tested this with a Hisense window unit and it is working.

2022-09-25 14:12 UTC, skotopes commented
@gsurkov can you check?

2022-09-26 10:25 UTC, gsurkov requested changes
Please change the file so that the signals of the same type are grouped together (e.g. Off signal should go after existing Off and so on)

2022-09-26 15:16 UTC, gsurkov approved these changes

2022-09-26 15:41 UTC, skotopes approved these changes

2022-09-26 15:42 UTC, merged