[FL-2797] Signal Generator app
flipperdevices/flipperzero-firmware pull request #1793
Opened 2022-09-27 15:46 UTC by nminaylov

# What's new

- [ Describe changes here ]

# Verification 

- [ Describe how to verify changes ]

# Checklist (For Reviewer)

- [ ] PR has description of feature/bug or link to Confluence/Jira task
- [ ] Description contains actions to verify feature/bugfix
- [ ] I've built this code, uploaded it to the device and verified feature/bugfix

2022-09-28 12:06 UTC, DrZlo13 requested changes

2022-09-28 12:06 UTC, DrZlo13 commented on firmware/targets/f7/furi_hal/furi_hal_pwm.h
> +void furi_hal_pwm_start(FuriHalPwmOutputId channel, uint32_t freq, uint8_t duty);
Documentation

2022-09-28 12:08 UTC, DrZlo13 commented on firmware/targets/f7/furi_hal/furi_hal_pwm.h
> +#pragma once
/**
 * @file furi_hal_pwm.h
 * PWM control HAL
 */

2022-09-28 16:35 UTC, skotopes approved these changes

2022-09-28 16:36 UTC, DrZlo13 approved these changes

2022-09-28 16:37 UTC, merged

2023-08-12 00:41 UTC, fuznutz73 commented
Any ideas on how to open the frequency possibilities below 1Hz (ie. 14.035 Hz, same as the NEW opticon receivers)?

2023-08-16 07:57 UTC, skotopes commented
@fuznutz73 use TIM2 to generate signal