[FL-2868] Remove string_push_uint64
flipperdevices/flipperzero-firmware pull request #1832
Opened 2022-10-05 15:29 UTC by Astrrra

# What's new

- Replaced string_push_uint64 with string_print in NFC parsers

# Verification 

- Read a plantain and a two cities card, verify the number

# Checklist (For Reviewer)

- [ ] PR has description of feature/bug or link to Confluence/Jira task
- [ ] Description contains actions to verify feature/bugfix
- [ ] I've built this code, uploaded it to the device and verified feature/bugfix

2022-10-05 15:57 UTC, skotopes requested changes

2022-10-05 15:57 UTC, skotopes commented on lib/nfc/parsers/plantain_4k_parser.c
> +    // string_t luhn_checksum_str;
Please remove dead code

2022-10-05 16:18 UTC, Astrrra commented on lib/nfc/parsers/plantain_4k_parser.c
> +    // string_t luhn_checksum_str;
Sorry, fixed now

2022-10-06 11:26 UTC, DrZlo13 submitted a review, later dismissed

2022-10-06 11:26 UTC, DrZlo13 commented on lib/nfc/parsers/plantain_4k_parser.c
> +#include "plantain_parser.h" // For luhn
plantain_calculate_luhn is not used, this header is not needed. Even if used, it should be moved to a separate library. Parsers should not include each other.

2022-10-06 11:45 UTC, Astrrra commented on lib/nfc/parsers/plantain_4k_parser.c
> +#include "plantain_parser.h" // For luhn
Makes sense

2022-10-06 18:50 UTC, skotopes approved these changes

2022-10-06 18:51 UTC, merged