[FL-2744] SPI Mem Manager C port
flipperdevices/flipperzero-firmware pull request #1860
Opened 2022-10-10 11:14 UTC by drunkbatya

# What's new

- new application - SPI Mem Manager, it allows reading, writing, comparing SPI chip dumps and erasing SPI chips

# Verification 

- try `./fbt launch_app APPSRC=applications/plugins/spi_mem_manager`, connect SPI chip to external SPI bus and test it. all functions should work

# Checklist (For Reviewer)

- [x] PR has description of feature/bug or link to Confluence/Jira task
- [x] Description contains actions to verify feature/bugfix
- [x] I've built this code, uploaded it to the device and verified feature/bugfix

2022-10-21 09:24 UTC, DrZlo13 commented on applications/plugins/spi_mem_manager/lib/spi/spi_mem_chip.c
> +const SPIMemChipVendorName SPIMemChipVendorNames[] = {
We use snake case for variables and function names, so `spi_mem_chip_vendor_names`.

2022-10-21 09:24 UTC, DrZlo13 commented on applications/plugins/spi_mem_manager/lib/spi/spi_mem_worker.h
> +} SPIMemWorker;
Do not export internal structures to entity API.

2022-12-02 20:54 UTC, AkechiShiro commented
Hey, I'd like to ask is this PR far from being finished, I've seen lots of commits being made, I'd like to know if there is any chance of it being planned soon for a near release?

2022-12-02 21:06 UTC, drunkbatya commented
> Hey, I'd like to ask is this PR far from being finished, I've seen lots of commits being made, I'd like to know if there is any chance of it being planned soon for a near release?

Hi! Thanks for interesting this app!
I think the first version will be included at the next firmware release. Before it we need to add support of most popular SPI chips, and do some tests.

2022-12-02 22:42 UTC, AkechiShiro commented
@drunkbatya Thanks, I'm aware that this might still be experimental, I hope I may be able to help with testing. 

Also, about adding more SPI flash chips, this might be of use, I'm not sure if [all the data from there could help]( https://www.flashrom.org/Supported_hardware#Supported_flash_chips), then a tracking issue could be created with checkboxes for each SPI flash that is planned to be supported, the FP Zero can support, I believe 3.3V/5V.

Question: 1.8V is not doable ? I don't know if the GPIOs can be set to 1.8V. Maybe later, it could be achieved? 

Once this draft PR merges into a release, best would be to be able to test the ones that are already supported (Winbonds chips I believe) first and see if reading/writing works alright (compared to a Raspberry Pi or any other device capable of read/writes to SPI chips).

A future feature, that could be worked on, once SPI reading/writing works alright is this : https://www.macronix.com/Lists/ApplicationNote/Attachments/1870/AN114v1-SFDP%20Introduction.pdf

2022-12-23 12:01 UTC, DrZlo13 requested changes

2022-12-23 12:01 UTC, DrZlo13 commented on applications/plugins/application.fam
> +        "bt_hid",
?

2022-12-23 12:01 UTC, DrZlo13 commented on applications/plugins/spi_mem_manager/application.fam
> +    stack_size=1 * 2048,
check stack via "ps" in cli

2022-12-23 12:01 UTC, DrZlo13 commented on applications/plugins/spi_mem_manager/lib/spi/spi_mem_chip_i.h
> +    uint8_t capacity_id;
group and align uint8_t values

2022-12-23 12:01 UTC, DrZlo13 commented on applications/plugins/spi_mem_manager/lib/spi/spi_mem_worker.c
> +    // furi_thread_set_priority(worker->thread, FuriThreadPriorityHigh);
Remove commented code

2022-12-23 12:01 UTC, DrZlo13 commented on applications/plugins/spi_mem_manager/lib/spi/spi_mem_worker.c
> +    furi_assert(worker->mode_index == SPIMemWorkerModeIdle);
furi_check?

2022-12-23 12:01 UTC, DrZlo13 commented on applications/plugins/spi_mem_manager/spi_mem_files.c
> +        size = storage_file_size(app->file);
storage_common_stat

2022-12-23 12:01 UTC, DrZlo13 commented on applications/plugins/spi_mem_manager/lib/spi/spi_mem_worker_modes.c
> +    size_t file_size = spi_mem_file_get_size(worker->cb_ctx);
Do not use callback context in non-callback functions

2022-12-23 12:01 UTC, DrZlo13 commented on applications/plugins/spi_mem_manager/lib/spi/spi_mem_worker_modes.c
> +        furi_delay_tick(10);
Comment please

2022-12-23 12:01 UTC, DrZlo13 commented on applications/plugins/spi_mem_manager/scenes/spi_mem_scene_read_filename.c
> +        size_t filename_start = furi_string_search_rchar(app->file_path, '/');
path_extract_dirname

2022-12-23 12:01 UTC, DrZlo13 commented on applications/plugins/spi_mem_manager/scenes/spi_mem_scene_verify.c
> +        if(event.event == SPIMemCustomEventViewVerifySkip) {
switch?

2022-12-23 12:01 UTC, DrZlo13 commented on applications/plugins/spi_mem_manager/views/spi_mem_view_progress.c
> +            size_t total_size = spi_mem_view_progress_set_total_size(model);
if(total_size == 0) total_size = 1;

2022-12-23 12:01 UTC, DrZlo13 commented on applications/plugins/spi_mem_manager/views/spi_mem_view_progress.h
> +View* spi_mem_view_progress_get_view(SPIMemProgressView* app);
Documentate functions

2022-12-23 12:01 UTC, DrZlo13 commented on applications/plugins/spi_mem_manager/tools/chiplist.xml
> +<?xml version="1.0" encoding="utf-8"?>
Add authors, links and license

2023-02-06 13:32 UTC, skotopes submitted a review, later dismissed

2023-02-06 13:32 UTC, skotopes commented on applications/plugins/spi_mem_manager/views/spi_mem_view_progress.h
> +View* spi_mem_view_progress_get_view(SPIMemProgressView* app);
?

2023-02-06 13:38 UTC, DrZlo13 requested changes

2023-02-06 13:38 UTC, DrZlo13 commented on applications/plugins/application.fam
> +        "bt_hid",
Still looks like a merge error.

2023-02-06 13:52 UTC, skotopes approved these changes

2023-02-06 13:53 UTC, hedger approved these changes

2023-02-06 14:02 UTC, DrZlo13 approved these changes

2023-02-06 14:03 UTC, merged