subghz: imp frequency history: replace mhz with a match count
flipperdevices/flipperzero-firmware pull request #1914
Opened 2022-10-23 07:22 UTC by Tardo

# What's new

Replace 'MHz' of frequency history with a match count.
Frequency history sorted by count

![flipper](https://user-images.githubusercontent.com/731270/197379496-c8fa9015-8786-4d0f-bf0a-53b19647ea92.png)

# Verification 

SubGHz Analyzer

# Checklist (For Reviewer)

- [ ] PR has description of feature/bug or link to Confluence/Jira task
- [ ] Description contains actions to verify feature/bugfix
- [ ] I've built this code, uploaded it to the device and verified feature/bugfix

2022-10-24 09:02 UTC, nuschpl commented
I think better idea is to keep on the main screen of freq analyser the original  form - having visibility to subsequent signals sequence  is more important for people who miss something on display in noisy environment. You can still do the 'statistics'  by switching it with some extra button, we could name it 'Group'

2022-10-25 07:14 UTC, Tardo commented
Some changes done. See first comment.

2022-10-26 00:47 UTC, skotopes requested changes

2022-10-26 00:47 UTC, skotopes commented on applications/main/subghz/views/subghz_frequency_analyzer.c
> +    SubGhzFrequencyAnalyzerLogFrequencyItem log_frequency[LOG_FREQUENCY_MAX_ITEMS];
How about m-array or m-list? In that case you can use m-algo for sorting.

2022-10-26 00:47 UTC, skotopes commented on applications/main/subghz/views/subghz_frequency_analyzer.c
> +    if((event->type == InputTypeRepeat) &&
There is InputTypeLong. But short press is totally ok here.

2022-10-26 00:47 UTC, skotopes commented on applications/main/subghz/views/subghz_frequency_analyzer.c
> +            sizeof(SubGhzFrequencyAnalyzerLogFrequencyItem) * num_items);
Looks dangerous. How about using m-lib for container and algorithms?

2022-10-27 05:39 UTC, Tardo commented
@skotopes changes done...  I think that now the RSSI is better represented... but take a look, maybe im wrong.

2022-10-28 12:21 UTC, DrZlo13 commented on applications/main/subghz/helpers/subghz_frequency_analyzer_log_item_array.c
> +FuriString*
`const char*` is enough here

2022-10-28 12:21 UTC, DrZlo13 submitted a review, later dismissed

2022-10-28 12:21 UTC, DrZlo13 commented on applications/main/subghz/helpers/subghz_frequency_analyzer_log_item_array.c
> +FuriString*
const char* is enough here

2022-10-28 12:41 UTC, skotopes requested changes

2022-10-28 12:41 UTC, skotopes commented on applications/main/subghz/helpers/subghz_frequency_analyzer_log_item_array.c
> +    subghz_frequency_analyzer_log_get_order_name(SubGhzFrequencyAnalyzerLogOrderBy order_by) {
Why not `const char*` ?

2022-10-28 12:41 UTC, skotopes commented on applications/main/subghz/views/subghz_frequency_analyzer.c
> +        with_view_model(
Crashing if you open Frequency analyzer, switch to log tab and press down.

```(gdb) bt
#0  0x0800ec6c in __furi_crash () at furi/core/check.c:102
#1  0x08006dd2 in MemManage_Handler () at firmware/targets/f7/furi_hal/furi_hal_interrupt.c:256
#2  <signal handler called>
#3  0x0806c146 in subghz_frequency_analyzer_input (event=0x2000cbd8, context=0x2000a9e0) at applications/main/subghz/views/subghz_frequency_analyzer.c:256
#4  0x0808429c in view_input (view=view@entry=0x2000aa18, event=event@entry=0x2000cbd8) at applications/services/gui/view.c:157
#5  0x08084be4 in view_dispatcher_handle_input (view_dispatcher=view_dispatcher@entry=0x2000a2e0, event=event@entry=0x2000cbd8) at applications/services/gui/view_dispatcher.c:262
#6  0x08084c96 in view_dispatcher_run (view_dispatcher=0x2000a2e0) at applications/services/gui/view_dispatcher.c:91
#7  0x0806e712 in subghz_app (p=0x0) at applications/main/subghz/subghz.c:369
#8  0x08011176 in furi_thread_body (context=0x200030a0) at furi/core/thread.c:79
#9  0x08011122 in furi_thread_catch () at furi/core/thread.c:51
```

2022-10-28 12:41 UTC, skotopes commented on applications/main/subghz/helpers/subghz_frequency_analyzer_log_item_array.h
> +#include <m-string.h>
Please use FuriString instead of m-string

2022-10-28 12:41 UTC, skotopes commented on applications/main/subghz/views/subghz_frequency_analyzer.c
> +#include <m-string.h>
Same here

2022-10-28 12:42 UTC, skotopes commented
Please un-draft when ready.

2022-10-28 20:22 UTC, Tardo commented
Changes done and tested!

2022-11-03 07:55 UTC, skotopes approved these changes

2022-11-03 07:57 UTC, merged