Snake Plugin: Store game state on close and restore it on restart, show highscore
flipperdevices/flipperzero-firmware pull request #1922
Opened 2022-10-24 16:28 UTC by JuanJakobo

# What's new

- Implements #1041 as it safes the current game state and restores it on restart
- Saves also an highscore to an file and shows the highscore on GameOver

# Verification 

- Open App and close it after moving a little bit around, reopen it and the state should be as before. 
- Close the App when GameOver Screen is shown. The Game should restart normal.
- Crash the snake and see if the highscore is shown. Do it again with an higher score and see if it increased, further do it with a lower score to verify if it stays the same.

# Checklist (For Reviewer)

- [ ] PR has description of feature/bug or link to Confluence/Jira task
- [ ] Description contains actions to verify feature/bugfix
- [ ] I've built this code, uploaded it to the device and verified feature/bugfix

2022-10-25 23:17 UTC, skotopes commented
@DrZlo13 is currently formalizing rules for ext apps storage layout. He'll be reviewer for this PR

2022-11-08 12:00 UTC, DrZlo13 commented
@JuanJakobo Hello!
I am now busy formalizing the rules for placing user files and supporting these rules in the firmware. It's enough for me for now if you put this file in "/ext/apps_data/snake_game".

2022-11-14 09:03 UTC, JuanJakobo commented
@DrZlo13 Hi, 
I moved the file storage to "/ext/apps_data/snake_game".

2022-12-10 20:19 UTC, skotopes commented
@DrZlo13 please review.

2022-12-12 17:50 UTC, skotopes requested changes

2022-12-12 17:50 UTC, skotopes commented on applications/plugins/snake_game/helpers/snake_file_handler.c
> +                return NULL;
Going to leak file if something will go wrong here.
Whole way of working with file looks quite dangerous, please check how it's done in other apps.

2022-12-12 17:50 UTC, skotopes commented on applications/plugins/snake_game/helpers/snake_file_handler.c
> +    Storage* storage = furi_record_open(RECORD_STORAGE);
Opening and closing storage record doesn't looks good here. The best option is to do it in allocator/deallocator of snake app itself and then pass it here.

2022-12-12 17:50 UTC, skotopes commented on applications/plugins/snake_game/helpers/snake_file_handler.c
> +                return NULL;
Leak here too

2022-12-12 17:50 UTC, skotopes commented on applications/plugins/snake_game/helpers/snake_file_handler.c
> +            return false;
We usually do {} while(0) and break. Please check how other apps do that

2022-12-12 17:51 UTC, skotopes commented
Please un-draft when ready ;-) And let me know if you need any help

2023-01-09 20:12 UTC, closed without merging

2023-03-13 20:56 UTC, fennectech commented
I can't tell whether this means it was merged or is dead.

2023-03-14 05:01 UTC, skotopes commented
@fennectech dead, PR was closed before merged