NFC: Accept non-parsed apps in Mifare DESFire.
flipperdevices/flipperzero-firmware pull request #2041
Opened 2022-11-22 14:30 UTC by mh-

Fixes #2040

# What's new

Accept non-parsed apps in Mifare DESFire.

# Verification 

Load this file from "Saved" in the NFC app
```
Filetype: Flipper NFC device
Version: 2
# Nfc device type can be UID, Mifare Ultralight, Mifare Classic
Device type: Mifare DESFire
# UID, ATQA and SAK are common for all formats
UID: 04 1B 2C EA 6B 3B 80
ATQA: 44 03
SAK: 20
# Mifare DESFire specific data
PICC Version: 04 01 01 01 00 16 05 04 01 01 01 04 16 05 04 1B 2C EA 6B 3B 80 BA 54 D3 9D 70 33 14
PICC Free Memory: 1760
PICC Change Key ID: 00
PICC Config Changeable: true
PICC Free Create Delete: true
PICC Free Directory List: true
PICC Key Changeable: true
PICC Max Keys: 01
PICC Key 0 Version: A2
Application Count: 2
Application IDs: 01 00 00 02 00 00
```

Before the PR, you will get a "Can not parse" error; 
after the PR, it will be possible to the emulate the UID.

# Checklist (For Reviewer)

- [x] PR has description of feature/bug or link to Confluence/Jira task
- [x] Description contains actions to verify feature/bugfix
- [x] I've built this code, uploaded it to the device and verified feature/bugfix

2022-11-24 09:07 UTC, gornekich requested changes
Hello @mh- 
I tested your file and your fix. It works fine.
However I can't reproduce this issue with any DESFire card I have. Could you show what data flipper shows just after you read this card?

2022-11-24 09:07 UTC, gornekich commented on lib/nfc/nfc_device.c
> +            if(!parsed_apps) {
Could you declare 
#define TAG "NfcDevice"
at the beginning and write logs just 
FURI_LOG_W(TAG, "Non-parsed apps found!");

And please delete commented code

2022-11-24 10:30 UTC, mh- commented
Hi @gornekich 
> However I can't reproduce this issue with any DESFire card I have. Could you show what data flipper shows just after you read this card?

These are screenshots:
![IMG_2397](https://user-images.githubusercontent.com/6257627/203747826-14a2bcbd-cb1c-4034-a275-1de3035eb187.jpg)
![IMG_2398](https://user-images.githubusercontent.com/6257627/203747822-7d086232-1638-4547-8968-6d5ea343c154.jpg)
![IMG_2399](https://user-images.githubusercontent.com/6257627/203747814-984f42b2-19ef-43f6-9398-51237b6db1d5.jpg)

Relevant logs:
```
106068 [I][NfcWorker] Mifare DESFire detected
106280 [W][MifareDESFire] Bad DESFire GET_KEY_SETTINGS response
106290 [W][MifareDESFire] Bad DESFire GET_KEY_SETTINGS response
125401 [W][nfc_device.c] before if(app->key_settings)  <-- this one added by me
```


In the firmware, when saving the file,
```
static bool nfc_device_save_mifare_df_app(FlipperFormat* file, MifareDesfireApplication* app) {
    bool saved = false;
    FuriString *prefix, *key;
    prefix =
        furi_string_alloc_printf("Application %02x%02x%02x", app->id[0], app->id[1], app->id[2]);
    key = furi_string_alloc();
    uint8_t* tmp = NULL;

    do {
        FURI_LOG_W("nfc_device.c", "before if(app->key_settings)");
        if(app->key_settings) {
            FURI_LOG_W("nfc_device.c", "if(app->key_settings)");
```
`app->key_settings` is `NULL`

2022-11-24 13:26 UTC, mh- commented
Also, this is what the NXP "TagInfo" Android app says about this particular card:
<img width="363" alt="image" src="https://user-images.githubusercontent.com/6257627/203795016-a9fce8fa-124c-45d8-8f3e-eb772ffa5183.png">
<img width="365" alt="image" src="https://user-images.githubusercontent.com/6257627/203795146-4855e547-1adb-4873-84bf-6d9df5d760b2.png">
<img width="369" alt="image" src="https://user-images.githubusercontent.com/6257627/203795426-61d6304d-442f-4f13-8132-8e6c87b32f6e.png">
<img width="370" alt="image" src="https://user-images.githubusercontent.com/6257627/203795503-f168a23d-7583-48e6-8259-b9c5ab1056dd.png">

2022-11-24 16:10 UTC, LowSkillDeveloper commented
I have the same problem  https://github.com/flipperdevices/flipperzero-firmware/issues/1904#issuecomment-1295952022 And after this fix, if I did not know about the existence of this bug, I would think that I was emulating the card in full, and not just its UID. 
Maybe it's worth to displaying a message on screen that only UID is emulated, without Application. At least until the possibility of full emulation is found.

2022-11-24 16:18 UTC, mh- commented
@LowSkillDeveloper 
> after this fix, if I did not know about the existence of this bug, I would think that I was emulating the card in full, and not just its UID.

Are you sure? On my Flipper, after loading a DESFire file from "Saved", the menu explicitly offers "Emulate UID", and not "Emulate" like with other non-DESFire files.

2022-11-24 16:25 UTC, LowSkillDeveloper commented
> Are you sure? On my Flipper, after loading a DESFire file from "Saved", the menu explicitly offers "Emulate UID", and not "Emulate" like with other non-DESFire files.

Ah, yes, you are right.
I just mean that it might be worth making a message that maybe the card may not perform all the functions or not work properly.
Perhaps the information in the log is enough, but not everyone reads them.

2022-11-24 16:50 UTC, gornekich approved these changes

2022-11-28 17:08 UTC, skotopes approved these changes

2022-11-28 17:14 UTC, merged