Second try. Add task 'Serial console' and group task with sequence calling
flipperdevices/flipperzero-firmware pull request #2121
Opened 2022-12-11 19:32 UTC by derskythe

# What's new

- Second try, [first one](https://github.com/flipperdevices/flipperzero-firmware/pull/2081) was close because my parent repo didn't forked from ofw
- Add task "Serial console" to call serial_cli.py
- Add task to show example of group tasks with run application and run console after it
- This example will be useful for those who are not so familiar with VSCode. I've seen this question a lot in Discord

# Verification 

- In VSCode run tasks: "Serial console", "[Debug] Launch App on Flipper with Serial Console"

# Checklist (For Reviewer)

- [ ] PR has description of feature/bug or link to Confluence/Jira task
- [ ] Description contains actions to verify feature/bugfix
- [ ] I've built this code, uploaded it to the device and verified feature/bugfix

2022-12-11 19:34 UTC, skotopes commented
@hedger please take a look when you have time

2022-12-11 19:37 UTC, skotopes commented
@derskythe Btw, no need to invite us to collaborate on your repository. When you create PR there is a checkbox, it's enough to keep it in default position so we can merge dev or push minor fixes.

2022-12-11 19:38 UTC, derskythe commented
@skotopes ок, sorry, understood.

2022-12-12 13:28 UTC, hedger requested changes

2022-12-12 13:28 UTC, hedger commented on .vscode/example/tasks.json
> +            "problemMatcher": [],
`            "group": "build",`
is missing

2022-12-12 13:28 UTC, hedger commented on .vscode/example/tasks.json
> +            "command": "./scripts/serial_cli.py",
uses system's python that might not have needed dependencies. Change to `./fbt cli`

2022-12-12 13:28 UTC, hedger commented on .vscode/example/tasks.json
> +            "group": "none",
for command to be visible in palette, has to be "build"

Also `            "problemMatcher": [],` is requried by [specs](https://code.visualstudio.com/docs/editor/tasks#_compound-tasks)

>Any background/watch tasks used in dependsOn with "dependsOrder": "sequence" must have a problem matcher that tracks when they are "done". The following task runs task Two, task Three, and then task One.

2022-12-12 17:52 UTC, skotopes commented
Please un-draft when ready

2022-12-12 19:26 UTC, derskythe commented
Fixed, also added FBT_NO_SYNC=0, because running fbt makes git calls

2022-12-14 07:36 UTC, hedger approved these changes

2022-12-14 07:42 UTC, merged