Move CSN space to revent overflow
flipperdevices/flipperzero-firmware pull request #2232
Opened 2022-12-31 04:34 UTC by bettse

# What's new

- Fix for https://github.com/flipperdevices/flipperzero-firmware/issues/2185
- Removes space between colon and first CSN byte.  Should allow enough room to fit a full 00's CSN.

# Verification 

- You could try to reproduce the bug and see it is fixed
- Alternatively just see the space has been moved and estimate that it'll correct the problem from the bug

# Checklist (For Reviewer)

- [ ] PR has description of feature/bug or link to Confluence/Jira task
- [ ] Description contains actions to verify feature/bugfix
- [ ] I've built this code, uploaded it to the device and verified feature/bugfix

2022-12-31 04:35 UTC, bettse commented
cc @pcunning

2023-01-06 18:57 UTC, skotopes requested changes

2023-01-06 18:57 UTC, skotopes commented on applications/plugins/picopass/scenes/picopass_scene_read_card_success.c
> +        furi_string_cat_printf(csn_str, "%02X ", csn[i]);
Nope, not going to fix issue ;-) Space is still space and it's handled when rendering. But even if you trim last space there will be not enough space.

2023-01-06 18:59 UTC, skotopes commented
Is it ok if we remove spaces between?

2023-01-07 18:12 UTC, bettse commented
Sorry for the delay, the idea was that the space _sometimes_ was too long, but since it doesn't wrap (as in the failure example) it would be offscreen whitespace.  Inelegant.  I'm 100% in favor or just removing the spaces.  I'll try to get around to that, but feel free to do it and close this out if I'm too slow.

2023-02-08 17:54 UTC, skotopes approved these changes

2023-02-08 18:06 UTC, merged