Firmware fixes and improvements via blackmagic
flipperdevices/flipperzero-firmware pull request #2321
Opened 2023-01-20 14:36 UTC by quen0n

# What's new

- Improved detection of blackmagic probe by USB
- Skipping the requirement to press "c" when flashing through blackmagic

# Verification 

- Flash the Flipper with blackmagic

# Checklist (For Reviewer)

- [ ] PR has description of feature/bug or link to Confluence/Jira task
- [ ] Description contains actions to verify feature/bugfix
- [ ] I've built this code, uploaded it to the device and verified feature/bugfix

2023-01-22 00:19 UTC, hedger commented on scripts/fbt_tools/blackmagic.py
> +                if str(port.location) == "None":
Can you please provide explanation and examples for this case?

2023-01-22 10:18 UTC, quen0n commented on scripts/fbt_tools/blackmagic.py
> +                if str(port.location) == "None":
In this case, port.location - is a sign of the Blackmagic debug port. The port for logs has a specific value. Thus, it is possible to detect the Blackmagic port, regardless of the order in which the ports were installed in the system.

```
COM2 {'device': 'COM2', 'name': 'COM2', 'description': 'Устройство с последовательным интерфейсом USB (COM2)', 'hwid': 'USB VID:PID=303A:4001 SER=BLACKMAGIC', 'vid': 12346, 'pid': 16385, 'serial_number': 'BLACKMAGIC', 'location': None, 'manufacturer': 'Корпорация Майкрософт', 'product': None, 'interface': None}
COM3 {'device': 'COM3', 'name': 'COM3', 'description': 'Устройство с последовательным интерфейсом USB (COM3)', 'hwid': 'USB VID:PID=303A:4001 SER=BLACKMAGIC LOCATION=1-3:x.2', 'vid': 12346, 'pid': 16385, 'serial_number': 'BLACKMAGIC', 'location': '1-3:x.2', 'manufacturer': 'Корпорация Майкрософт', 'product': None, 'interface': None}      
```
Here are two com ports that are determined when connecting blackmagic. Here you can compare locations.

2023-01-24 15:10 UTC, hedger approved these changes, later dismissed

2023-01-30 08:08 UTC, skotopes commented
also un-draft when ready

2023-02-08 09:46 UTC, hedger commented on scripts/fbt_tools/blackmagic.py
> +                if str(port.location) == "None":
On my system, all ports have a valid Locaiton:
```
./fbt get_blackmagic
COM15 {'device': 'COM15', 'name': 'COM15', 'description': 'Устройство с последовательным интерфейсом USB (COM15)', 'hwid': 'USB VID:PID=303A:4001 SER=BLACKMAGIC LOCATION=1-5:x.2', 'vid': 12346, 'pid': 16385, 'serial_number': 'BLACKMAGIC', 'location': '1-5:x.2', 'manufacturer': 'Microsoft', 'product': None, 'interface': None}
COM16 {'device': 'COM16', 'name': 'COM16', 'description': 'Устройство с последовательным интерфейсом USB (COM16)', 'hwid': 'USB VID:PID=303A:4001 SER=BLACKMAGIC LOCATION=1-5:x.0', 'vid': 12346, 'pid': 16385, 'serial_number': 'BLACKMAGIC', 'location': '1-5:x.0', 'manufacturer': 'Microsoft', 'product': None, 'interface': None}
scons: *** [phony_get_blackmagic] Blackmagic probe not found
```

2023-02-08 09:48 UTC, skotopes requested changes

2023-02-08 09:48 UTC, skotopes commented on scripts/fbt_tools/blackmagic.py
> +                if str(port.location) == "None":
Why not to use `if port.location is None:` ? str(None) looks a little bit too much...

2023-02-08 09:50 UTC, skotopes commented
Un-draft when ready

2023-02-08 10:12 UTC, quen0n commented on scripts/fbt_tools/blackmagic.py
> +                if str(port.location) == "None":
Okay, then will need to find another way to determine the fidelity of the blackmagic port ¯\_(ツ)_/¯

2023-02-08 10:14 UTC, quen0n commented on scripts/fbt_tools/blackmagic.py
> +                if str(port.location) == "None":
Tell me, what version of Blackmagic firmware are you using? So I can test different options

2023-02-08 18:06 UTC, quen0n commented
I reverted the changes that were related to the definition of the Blackmagic port, since there will be a dap-link in the future. The remaining change is to skip pressing C when flashing.

2023-02-08 18:09 UTC, skotopes approved these changes

2023-02-08 18:09 UTC, hedger approved these changes

2023-02-08 18:10 UTC, skotopes approved these changes

2023-02-09 03:40 UTC, merged