emv: parse track1&2 equivalent data
flipperdevices/flipperzero-firmware pull request #2332
Opened 2023-01-23 15:15 UTC by emilytrau

# What's new

- Expose Track 1 and Track 2 magnetic stripe equivalent data if available
  - May be handy as an input method for magspoof! (cc @zacharyweiss)
- Use track 2 as an additional source for card expiry in case `EMV_TAG_EXP_DATE` isn't supported

References:
- EMV 4.4 Book 3: Application Specification, Annex A
- https://iso8583.info/lib/MasterCard/M_Chip/4/TLVs
- https://iso8583.info/lib/VISA/VCPS/TLVs

# Verification 

- Scan a debit/credit card
- `NFC -> Read -> Info` should display Track 2 data for most EMV cards
- MasterCard's are also known to provide Track 1 data

# Checklist (For Reviewer)

- [x] PR has description of feature/bug or link to Confluence/Jira task
- [x] Description contains actions to verify feature/bugfix
- [x] I've built this code, uploaded it to the device and verified feature/bugfix

2023-01-23 20:36 UTC, zacharyweiss commented
Interesting! Thanks for the tag; I was under the impression no EMV cards exposed all the fields one needs for magstripe data unencrypted (missing vital things like CVV, etc). I likely won't be digging on this much as my current focus is lower-level emulation improvements & access cards (and I'm slightly worried by abuse potential in building out dedicated payment card functions), but I'll happily accept any PRs to my (very messy) code if you find a way to do it.

2023-01-24 10:59 UTC, gornekich commented
Hi @emilytrau 
Thanks for PR. I am testing it right now. Could you please give access to merge current dev to your branch? You should have the check box for this when you made your PR.

2023-01-24 11:02 UTC, emilytrau commented
Hi @gornekich. I've made sure edits by maintainers is on. Thanks for testing :)

2023-01-24 12:00 UTC, gornekich commented
@emilytrau now I can see that I have all necessary accesses, sorry :)

Additional source of expiration date works great, thank you!
Why do you think Track 1 and Track 2 data is worth to be displayed on the screen? We already parse all useful data from this tags, and separate lines with raw data on info screen looks unnecessary from my point of view

2023-01-24 12:02 UTC, emilytrau commented
I'm not completely happy with the additional clutter on the info screen either to be honest. It's slightly interesting but not all that important. Don't mind leaving it out

2023-01-24 13:15 UTC, gornekich requested changes
@emilytrau thanks for changes!
I would go further and delete track_x_equiv and track_x_equiv_len from EmvData structure. Since we don't use this data in application, it's not necessary to store this data. You can declare this variables locally for logging data.

Also, please avoid force push, because other people who use your brunch have to resolve local conflicts.

2023-01-24 13:15 UTC, gornekich commented on lib/nfc/protocols/emv.h
> +    uint8_t track_2_equiv_len;
I would delete this fields

2023-01-24 13:15 UTC, gornekich commented on lib/nfc/nfc_worker.c
> +    }
No need in passing data to applications

2023-01-24 13:15 UTC, gornekich commented on lib/nfc/protocols/emv.c
> +                success = true;
you can make track_x_equiv and track_x_equiv_len locally here

2023-01-25 07:53 UTC, gornekich approved these changes
Thank you!

2023-01-27 05:08 UTC, skotopes approved these changes

2023-01-27 05:10 UTC, merged