fbt, faploader: minimal app module implementation
flipperdevices/flipperzero-firmware pull request #2420
Opened 2023-02-22 21:12 UTC by hedger

# What's new

- [ Describe changes here ]

# Verification 

- [ Describe how to verify changes ]

# Checklist (For Reviewer)

- [ ] PR has description of feature/bug or link to Confluence/Jira task
- [ ] Description contains actions to verify feature/bugfix
- [ ] I've built this code, uploaded it to the device and verified feature/bugfix

2023-03-01 09:45 UTC, Milk-Cool commented
it won't break anything right?

2023-03-02 13:18 UTC, hedger commented
@Milk-Cool only apps that were using FlipperAppType.PLUGIN. It had been marked as not-to-be-used a long time ago, and it changes meaning in this PR.

Also there are some directory structure changes.

2023-03-14 11:50 UTC, skotopes approved these changes, later dismissed

2023-03-14 13:17 UTC, DrZlo13 requested changes

2023-03-14 13:17 UTC, DrZlo13 commented on lib/flipper_application/elf/elf_file.h
> +bool elf_file_is_init_complete(ELFFile* elf);
docs

2023-03-14 14:24 UTC, skotopes approved these changes

2023-03-14 14:24 UTC, DrZlo13 approved these changes

2023-03-14 14:29 UTC, merged