[FL-1799] Require the trailing slash for paths
flipperdevices/flipperzero-firmware pull request #2486
Opened 2023-03-13 18:49 UTC by Astrrra

# What's new

- Storage paths like "/internal", "/international", "/anyone" etc are not valid anymore.

# Verification 

- storage write /int/ernational
- write anything
- storage stat /international should result in an error
- storage read /International should result in an error as well

# Checklist (For Reviewer)

- [ ] PR has description of feature/bug or link to Confluence/Jira task
- [ ] Description contains actions to verify feature/bugfix
- [ ] I've built this code, uploaded it to the device and verified feature/bugfix

2023-03-13 19:23 UTC, hedger requested changes
INT & EXT are swapped

2023-03-14 10:29 UTC, hedger approved these changes, later dismissed

2023-03-14 10:32 UTC, DrZlo13 submitted a review, later dismissed
Will not work with `/int` path. For example `storage list /int`.

2023-03-16 08:27 UTC, skotopes approved these changes

2023-03-16 08:28 UTC, merged