[FL-3284] Fix reading Mifare Classic cards with unusual access conditions and fix emulation of unknown keys
flipperdevices/flipperzero-firmware pull request #2620
Opened 2023-04-26 21:34 UTC by Astrrra

# What's new

- Fixes one of the problems in #2577 (reading 30 keys instead of the actual 31 known keys)
- When emulating Mifare Classic with unknown keys the Flipper does not assume that the unknown keys are 00000000000 anymore.

# Verification 

- Include the non-standard keys in the user dict and read the dump from #2577, make sure that 31 keys are found.
- Emulate a card with unknown keys, try authenticating to the unknown sectors with 00000000000 as a key, make sure that the authentication fails.

# Checklist (For Reviewer)

- [ ] PR has description of feature/bug or link to Confluence/Jira task
- [ ] Description contains actions to verify feature/bugfix
- [ ] I've built this code, uploaded it to the device and verified feature/bugfix

2023-05-01 23:49 UTC, xMasterX commented
Hi, `Detect reader` will not collect any nonces with changes introduced in this PR
Something is not right with changes in this file, can't say what exactly, haven't checked further
`lib/nfc/protocols/mifare_classic.c`

2023-05-24 16:46 UTC, Astrrra commented
@xMasterX nice catch, thanks! Will fix soon

2023-06-08 05:34 UTC, skotopes requested changes

2023-06-08 05:34 UTC, skotopes commented on lib/nfc/nfc_worker.c
> +                       found_key == current_key) {
comparing pointers instead of comparing content is clearly incorrect here

2023-06-08 05:34 UTC, skotopes commented on lib/nfc/nfc_worker.c
> +                       found_key == current_key) {
same

2023-06-09 12:36 UTC, skotopes approved these changes

2023-06-09 12:41 UTC, merged