Update ac.ir
flipperdevices/flipperzero-firmware pull request #2701
Opened 2023-05-25 18:55 UTC by technobulb

Added Model: Danby DAC060EB7WDB

# What's new

Added Model: Danby DAC060EB7WDB
Sold at costco

# Checklist (For Reviewer)

-I am new to coding so please let me know if there is anything needing correction

2023-05-25 19:15 UTC, gsurkov requested changes

2023-05-25 19:15 UTC, gsurkov commented on assets/resources/infrared/assets/ac.ir
> +name: Fan_hi
There are no `Fan_hi` and `Fan_lo` signals names in the file format. 
Please see the [documentation](https://github.com/flipperdevices/flipperzero-firmware/blob/dev/documentation/UniversalRemotes.md#air-conditioners) for available signal names.

2023-05-25 19:39 UTC, technobulb reviewed
Removed Fan

2023-05-25 19:39 UTC, technobulb commented on assets/resources/infrared/assets/ac.ir
> +name: Fan_hi
Ok I fixed. Sorry didnt realize we were limited to those, thought that was the minimum

2023-05-26 10:04 UTC, gsurkov approved these changes

2023-05-26 13:02 UTC, skotopes approved these changes

2023-05-26 13:12 UTC, merged

2023-05-28 02:11 UTC, technobulb commented
Thanks. It seems like you add this to the universal codes. How can I add this to my flipper in the universal file instead of standalone preset? Does you add it in the next software update?