NFC: Improved MFC emulation on some readers
flipperdevices/flipperzero-firmware pull request #2825
Opened 2023-07-01 20:07 UTC by AloneLiberty

# What's new

- [ Describe changes here ]

# Verification 

- `nfc-mfclassic r a u dump` on ACR122U should work now

# Checklist (For Reviewer)

- [ ] PR has description of feature/bug or link to Confluence/Jira task
- [ ] Description contains actions to verify feature/bugfix
- [ ] I've built this code, uploaded it to the device and verified feature/bugfix

2023-07-10 11:12 UTC, giacomoferretti commented
Works for me!
Tested on ACR122U, gonna test it soon with MCT on Android.

Should fix #1862 and maybe even #2577.

2023-07-11 16:32 UTC, gornekich requested changes
Hello @AloneLiberty ! Thanks for PR. Tested it and it works good.

Please, make some changes I mentioned and we will merge your PR

2023-07-11 16:32 UTC, gornekich commented on lib/nfc/protocols/mifare_classic.c
> +            return false;
Please, avoid return from the body of function. It's not safe if you allocate memory above return and exit from function before freeing that memory. Also it make code less readable.

I suggest rename variable `command_processed` -> `send_nack` and add new variable `need_reset`. Rework every place where you write `return` with filling these variables then call `break`. And return `need_reset` at the and of the function

2023-07-11 16:32 UTC, gornekich commented on lib/nfc/protocols/mifare_classic.c
> +                    return false;
Same here and below

2023-07-12 08:39 UTC, gornekich approved these changes
Thanks

2023-07-12 09:13 UTC, skotopes approved these changes

2023-07-12 09:14 UTC, merged