[FL-870] Auto-generated firmware documentation take two
flipperdevices/flipperzero-firmware pull request #2944
Opened 2023-08-04 08:50 UTC by Astrrra

# What's new

- [ Describe changes here ]

# Verification 

- [ Describe how to verify changes ]

# Checklist (For Reviewer)

- [ ] PR has description of feature/bug or link to Confluence/Jira task
- [ ] Description contains actions to verify feature/bugfix
- [ ] I've built this code, uploaded it to the device and verified feature/bugfix

2024-02-16 09:52 UTC, skotopes requested changes
Please check all generated pages for formatting error

2024-02-16 09:52 UTC, skotopes commented on documentation/.gitignore
> +/doxygen/build
also please add generated docs folder to ignore too

2024-02-16 09:52 UTC, skotopes commented
un-draft when ready

2024-02-19 09:13 UTC, drunkbatya submitted a review, later dismissed

2024-03-06 06:21 UTC, skotopes approved these changes

2024-03-06 06:25 UTC, merged