Scripts: OB recovery
flipperdevices/flipperzero-firmware pull request #2964
Opened 2023-08-09 12:17 UTC by skotopes

# What's new

- Scripts: OB recovery

# Verification 

- Damage OB(not sure how), recover with `./scripts/ob.py -d recover --interface=interface/stlink.cfg`

# Checklist (For Reviewer)

- [ ] PR has description of feature/bug or link to Confluence/Jira task
- [ ] Description contains actions to verify feature/bugfix
- [ ] I've built this code, uploaded it to the device and verified feature/bugfix

2023-08-09 12:25 UTC, DrZlo13 requested changes

2023-08-09 12:25 UTC, DrZlo13 commented on scripts/flipper/utils/programmer_openocd.py
> +        self.openocd.send_tcl("mww 0x58004008 0x45670123")
`stm32.flash_unlock
`

2023-08-09 12:25 UTC, DrZlo13 commented on scripts/flipper/utils/programmer_openocd.py
> +        self.openocd.send_tcl("mww 0x5800400c 0x08192A3B")
`stm32.option_bytes_unlock`

2023-08-09 20:45 UTC, skotopes commented on scripts/flipper/utils/programmer_openocd.py
> +        self.openocd.send_tcl("mww 0x5800400c 0x08192A3B")
magic sequence

2023-08-09 20:45 UTC, skotopes commented on scripts/flipper/utils/programmer_openocd.py
> +        self.openocd.send_tcl("mww 0x58004008 0x45670123")
magic sequence

2023-08-10 08:51 UTC, DrZlo13 submitted a review, later dismissed

2023-08-10 09:44 UTC, DrZlo13 approved these changes

2023-08-10 09:45 UTC, merged