furi_hal: add selecting speed and USART for logging output
flipperdevices/flipperzero-firmware pull request #3078
Opened 2023-09-14 10:10 UTC by Skorpionm

# What's new

- [ Describe changes here ]

# Verification 

- [ Describe how to verify changes ]

# Checklist (For Reviewer)

- [ ] PR has description of feature/bug or link to Confluence/Jira task
- [ ] Description contains actions to verify feature/bugfix
- [ ] I've built this code, uploaded it to the device and verified feature/bugfix

2023-10-06 12:38 UTC, skotopes requested changes

2023-10-06 12:38 UTC, skotopes commented on applications/main/gpio/usb_uart_bridge.c
> +    uint8_t data[data_len];
don't allocate data on stack with variable passed from outside

2023-10-06 12:38 UTC, skotopes commented on applications/main/gpio/usb_uart_bridge.c
> +    furi_stream_buffer_send(usb_uart->rx_stream, data, data_len, 100);
no timeouts in interrupts

2023-10-06 12:38 UTC, skotopes commented on firmware/targets/f7/furi_hal/furi_hal_uart.c
> +    furi_assert(uart[ch] != NULL && uart[ch]->buffer_rx_ptr != NULL);
FURI_IS_IRQ_MODE check

2023-10-06 12:38 UTC, skotopes commented on firmware/targets/f7/furi_hal/furi_hal_uart.c
> +size_t furi_hal_uart_dma_bytes_available(FuriHalUartId ch) {
private

2023-10-07 13:23 UTC, Skorpionm commented on applications/main/gpio/usb_uart_bridge.c
> +    uint8_t data[data_len];
+

2023-10-07 13:24 UTC, Skorpionm commented on applications/main/gpio/usb_uart_bridge.c
> +    furi_stream_buffer_send(usb_uart->rx_stream, data, data_len, 100);
fix

2023-10-07 13:24 UTC, Skorpionm commented on firmware/targets/f7/furi_hal/furi_hal_uart.c
> +    furi_assert(uart[ch] != NULL && uart[ch]->buffer_rx_ptr != NULL);
fix

2023-10-07 13:24 UTC, Skorpionm commented on firmware/targets/f7/furi_hal/furi_hal_uart.c
> +size_t furi_hal_uart_dma_bytes_available(FuriHalUartId ch) {
fix

2024-02-17 07:36 UTC, closed without merging