Berezhnoy/felica listener
flipperdevices/flipperzero-firmware pull request #3190
Opened 2023-11-02 09:22 UTC by RebornedBrain

# What's new

Flipper now can emulate FeliCa UID

# Verification 

Read and save some FeliCa, then open this card and select "Emulate UID"
Then try to read it with another Flipper :)
# Checklist (For Reviewer)

- [ ] PR has description of feature/bug or link to Confluence/Jira task
- [ ] Description contains actions to verify feature/bugfix
- [ ] I've built this code, uploaded it to the device and verified feature/bugfix

2023-11-02 15:59 UTC, gornekich requested changes
Neet to fill PTSSN memory correctly

2023-11-20 10:36 UTC, gornekich requested changes

2023-11-20 10:36 UTC, gornekich commented on lib/nfc/protocols/felica/felica_listener.c
> +    furi_assert(event.event_data);
Remove duplication

2023-11-22 09:54 UTC, gornekich approved these changes

2023-11-26 08:04 UTC, skotopes approved these changes

2023-11-26 08:10 UTC, merged