[FL-3675] Ntag21x write
flipperdevices/flipperzero-firmware pull request #3246
Opened 2023-11-27 18:59 UTC by RebornedBrain

# What's new
Now Flipper can write user data from one stored NTAG21x to another presented card.

There are several checks to be passed in order to write successfully:
- Write and presented cards must be of the same type NTAG213 - NTAG213, NTAG215 - NTAG215, NTAG216 - NTAG216
- Presented card must have default PWD, PACK and disabled AUTH0
- Static and dynamic lock bits on the presented card must be 0, which guaranties that all user memory is unlocked.

# Verification 
**Case 1:**
- On some stored or fresh read NTAG213 choose "Write" button
- Then present another NTAG213 fresh to flipper.
**Result:** Writting success screen and data written to the presented card.

**Case 2:**
- On some stored or fresh read NTAG213 choose "Write" button
- Then present another NOT NTAG213 fresh to flipper.
**Result:** "This is wrong card" screen and no data written to the presented card.  

**Case 3:**
- On some stored or fresh read NTAG213 choose "Write" button
- Then present another NTAG213 with pwd set to flipper.
**Result:** "Writting gone wrong" screen and no data written to the presented card.  

**Case 4:**
- On some stored or fresh read NTAG213 choose "Write" button
- Then present another NTAG213 with static or dynamic lock bits set to flipper.
**Result:** "Writting gone wrong" screen and no data written to the presented card.  

# Checklist (For Reviewer)

- [ ] PR has description of feature/bug or link to Confluence/Jira task
- [ ] Description contains actions to verify feature/bugfix
- [ ] I've built this code, uploaded it to the device and verified feature/bugfix

2023-12-01 10:08 UTC, gornekich requested changes

2023-12-01 10:08 UTC, gornekich commented on applications/main/nfc/scenes/nfc_scene_mf_ultralight_write_fail.c
> +    return consumed;
We can come from NfcSceneReadMenu

2023-12-01 10:38 UTC, RebornedBrain commented on applications/main/nfc/scenes/nfc_scene_mf_ultralight_write_fail.c
> +    return consumed;
@gornekich I've added that

2023-12-01 12:35 UTC, gornekich submitted a review, later dismissed

2023-12-02 04:41 UTC, skotopes approved these changes

2023-12-02 04:45 UTC, merged