NfcDict Refactoring
flipperdevices/flipperzero-firmware pull request #3271
Opened 2023-12-05 22:18 UTC by v0lp3

# What's new

I refactored the NfcDict structure to make it more generic,  so now we can use it with other applications like RFID (for example if we implement dictionary attack on T5577 password). The NfcDict was renamed KeysList and was moved into toolbox, therefore MfUserDict wraps this structure.

# Verification 

Test NFC application.

# Checklist (For Reviewer)

- [ ] PR has description of feature/bug or link to Confluence/Jira task
- [ ] Description contains actions to verify feature/bugfix
- [ ] I've built this code, uploaded it to the device and verified feature/bugfix

2023-12-05 23:02 UTC, hedger commented on targets/f7/api_symbols.csv
> +Version,v,50.0,,
don't leave "v" here.

Build both targets locally first: `./fbt TARGET_HW=18 updater_package`

2023-12-07 03:08 UTC, skotopes commented
@v0lp3 also keep in mind that there are other apps that using nfc dict (picopass) that is going to be broken by those changes

2023-12-07 03:36 UTC, v0lp3 commented
> @v0lp3 also keep in mind that there are other apps that using nfc dict (picopass) that is going to be broken by those changes

I see. How about we retain the nfc_dict.* files or replace function in nfc_dict.h with inlines to ensure compatibility?

2023-12-07 03:44 UTC, skotopes commented
@v0lp3 good question, let's wait for @gornekich comment on this PR.

2023-12-13 13:59 UTC, gornekich requested changes
Please, rename KeysList to KeysDict and rework nfc application with KeysDict. No need to support old symbols. I will rework picopass app to use new KeysDict by my self.

So, the scope of this PR should be moving NfcDict to KeysDict in toolbox

2023-12-13 13:59 UTC, gornekich commented on applications/main/nfc/scenes/nfc_scene_config.h
> -ADD_SCENE(nfc, mf_classic_keys_list, MfClassicKeysList)
Undo this change

2023-12-13 19:20 UTC, v0lp3 commented
> Please, rename KeysList to KeysDict and rework nfc application with KeysDict. No need to support old symbols. I will rework picopass app to use new KeysDict by my self.
> 
> So, the scope of this PR should be moving NfcDict to KeysDict in toolbox

Ok done

2023-12-14 09:10 UTC, gornekich commented
@v0lp3 please, fix unit tests.
Run `./fbt FIRMWARE_APP_SET=unit_tests` to build firmware with unit tests. Then connect to cli via `./fbt cli`, run `unit_tests nf`c and make sure all tests are passed

2023-12-14 13:06 UTC, v0lp3 commented
> @v0lp3 please, fix unit tests. Run `./fbt FIRMWARE_APP_SET=unit_tests` to build firmware with unit tests. Then connect to cli via `./fbt cli`, run `unit_tests nf`c and make sure all tests are passed

How can i configure a mock flipper zero device?

2023-12-14 14:38 UTC, gornekich commented
> > @v0lp3 please, fix unit tests. Run `./fbt FIRMWARE_APP_SET=unit_tests` to build firmware with unit tests. Then connect to cli via `./fbt cli`, run `unit_tests nf`c and make sure all tests are passed
> 
> How can i configure a mock flipper zero device?

Don't understand your problem. Do you have flipper to test your changes?

2023-12-14 16:12 UTC, v0lp3 commented
I was wondering if it is a problem to run unit tests with PR GitHub actions. I read that the device used in the actions is mock and I was wondering if it would be possible to replicate the configuration in my own environment

2023-12-14 16:13 UTC, v0lp3 commented
> > > @v0lp3 please, fix unit tests. Run `./fbt FIRMWARE_APP_SET=unit_tests` to build firmware with unit tests. Then connect to cli via `./fbt cli`, run `unit_tests nf`c and make sure all tests are passed
> > 
> > 
> > How can i configure a mock flipper zero device?
> 
> Don't understand your problem. Do you have flipper to test your changes?

I was wondering if it is a problem to run unit tests with PR GitHub actions. I read that the device used in the actions is mock and I was asking you if it would be possible to replicate the configuration in my own environment.

2023-12-15 13:35 UTC, gornekich requested changes

2023-12-15 13:35 UTC, gornekich commented on lib/nfc/protocols/mf_classic/mf_classic.h
> +}
Please, delete these mf_classic_dict* functions here and below. It's totally OK if nfc app will use KeysDict directly.

2023-12-15 13:35 UTC, gornekich commented on lib/nfc/protocols/mf_classic/mf_classic.h
> +
Unnecessary types

2023-12-15 13:35 UTC, gornekich commented on lib/toolbox/keys_dict.c
> +static inline void __add_ending_new_line(KeysDict* instance) {
Please, avoid such naming. Even static functions should starts with lib name. This function should be names keys_dict_add_ending_new_line

2023-12-15 13:35 UTC, gornekich commented on lib/toolbox/keys_dict.c
> +static inline bool __read_key_line(KeysDict* instance, FuriString* line, bool* is_endfile) {
Same here. keys_dict_read_line()

2023-12-15 13:35 UTC, gornekich commented on lib/toolbox/keys_dict.c
> +    else {
Please, add here and below brackets {}. It will be much easier to read and allows to avoid mistakes in future.

2023-12-15 13:38 UTC, gornekich commented
> I was wondering if it is a problem to run unit tests with PR GitHub actions. I read that the device used in the actions is mock and I was asking you if it would be possible to replicate the configuration in my own environment.

I see that you fixed unit tests. Running locally `unit_tests` in CLI is equivalent to CI tests

2023-12-18 12:31 UTC, gornekich approved these changes
Well done, thanks!

2023-12-18 14:30 UTC, skotopes approved these changes

2023-12-18 14:30 UTC, merged