ble: profile rework
flipperdevices/flipperzero-firmware pull request #3272
Opened 2023-12-06 16:54 UTC by hedger

# What's new

- [ Describe changes here ]

# Verification 

- [ Describe how to verify changes ]

# Checklist (For Reviewer)

- [ ] PR has description of feature/bug or link to Confluence/Jira task
- [ ] Description contains actions to verify feature/bugfix
- [ ] I've built this code, uploaded it to the device and verified feature/bugfix

2024-01-15 17:11 UTC, skotopes requested changes

2024-01-15 17:11 UTC, skotopes commented on applications/examples/example_ble_beacon/ble_beacon_app.h
> +#define TEXT_STORE_SIZE 64U
remove

2024-01-15 17:11 UTC, skotopes commented on applications/main/nfc/plugins/supported_cards/opal.c
> +#include "core/common_defines.h"
`<>`

2024-01-15 17:11 UTC, skotopes commented on applications/services/bt/bt_service/bt.h
> +#include <core/common_defines.h>
remove?

2024-01-15 17:11 UTC, skotopes commented on applications/services/cli/cli_commands.c
> +    uint32_t thread_num = furi_thread_enumerate(threads_ids, run_times, threads_num_max);
Use DWT as time source
Snapshot values on start
Wait for 1 second
Get another values and calculate diff
Show 1 second usage


or make TOP command where you do it in cycle + sort processes by id/name

2024-01-15 17:11 UTC, skotopes commented on lib/ble_profile/extra_profiles/hid_profile.c
> +    // .process = NULL,
remove

2024-01-15 17:11 UTC, skotopes commented on targets/f7/ble_glue/ble_system.c
> +void shci_cmd_resp_wait(uint32_t timeout) {
nope, remove it)

2024-01-15 17:11 UTC, skotopes commented on targets/f7/ble_glue/furi_ble/event_dispatcher.c
> +    SVCCTL_RegisterSvcHandler(ble_service_event_dispatcher_dispatch_event);
Override weak symbols like SVCCTL_UserEvtRx and serve it from your code

2024-01-15 17:11 UTC, skotopes commented on targets/furi_hal_include/furi_hal_ble.h
> +#include "core/string.h"
remove

2024-01-15 17:11 UTC, skotopes commented on targets/furi_hal_include/furi_hal_ble.h
> +#define FURI_HAL_BLE_C2_START_TIMEOUT 1000
ciferki v skobochkah

2024-01-31 02:24 UTC, thejudge156 commented
@hedger Would you be open to a PR to your branch that adds a OpenHaystack profile?

2024-02-02 10:36 UTC, hedger commented
@thejudge156 you can bring that profile along with your custom app. Just implement the profile interface.

2024-02-02 17:50 UTC, thejudge156 commented
Thanks for the pointer, I will work on that.

2024-02-16 07:06 UTC, skotopes approved these changes

2024-02-16 07:20 UTC, merged