nfc_util: little endian bytes2num functions added
flipperdevices/flipperzero-firmware pull request #3287
Opened 2023-12-12 13:22 UTC by Leptopt1los

# What's new

- nfc_util_bytes2num_little_endian function added

Problem: 
When developing parsers, i often come across cards in which data is stored in little endian. in nfc_util.c there is a function uint64_t nfc_util_bytes2num(const uint8_t* src, uint8_t len), which reads len bytes at the src pointer and returns them as a number. The problem is that it reads them as big endian, and there is no alternative. Accordingly, for each such case I have to write an extra loop and read everything manually

This feature will solve the problem

# Verification 

- test that the function does not go beyond boundaries
- test the correctness of operation (the result is indeed a representation of the little endian number stored in the src)

# Checklist (For Reviewer)

- [ ] PR has description of feature/bug or link to Confluence/Jira task
- [ ] Description contains actions to verify feature/bugfix
- [ ] I've built this code, uploaded it to the device and verified feature/bugfix

2023-12-12 13:28 UTC, hedger requested changes, later dismissed
Please sync changes across all targets (`./fbt TARGET_HW=18`).

2023-12-12 13:49 UTC, Leptopt1los commented
> Please sync changes across all targets (`./fbt TARGET_HW=18`).

done

2023-12-13 09:29 UTC, gornekich submitted a review, later dismissed

2023-12-15 16:49 UTC, skotopes approved these changes

2023-12-15 17:05 UTC, merged