ITSO Parser (UK)
flipperdevices/flipperzero-firmware pull request #3325
Opened 2023-12-28 16:58 UTC by gsp8181

# What's new

- ITSO parser added to NFC app. ITSO is a standard for UK transport cards (aside from Oyster). Used for rail, bus and subway passes across GB. This parser grabs the card number and expiry date. More information is available on the card but locked behind propriety apps and an extensive database of station stops and operators is needed.

# Verification 

- Scan an ITSO card and verify that the number matches the number printed on the card. Expiry date will match if printed on the card.

# Checklist (For Reviewer)

- [ ] PR has description of feature/bug or link to Confluence/Jira task
- [ ] Description contains actions to verify feature/bugfix
- [ ] I've built this code, uploaded it to the device and verified feature/bugfix

2023-12-28 17:51 UTC, gornekich commented
Hello @gsp8181 ! Thanks for PR!
Could you please share example .nfc file to verify your PR? You can send it here or DM me in Discord gornekich

2024-01-10 11:29 UTC, gornekich requested changes
Hello @gsp8181 
Sorry for late review. I tested you PR, everything works great!
Please, make some changes to make code look better and we will merge PR.

2024-01-10 11:29 UTC, gornekich commented on applications/main/nfc/plugins/supported_cards/itso.c
> +}
Please, move this function to furi_hal_rtc.h and rename to furi_hal_rtc_timestamp_to_datetime().

2024-01-10 11:29 UTC, gornekich commented on applications/main/nfc/plugins/supported_cards/itso.c
> +    ((((year) % 4 == 0) && ((year) % 100 != 0)) || ((year) % 400 == 0))
After moving timestamp_to_datetime() function to furi_hal_rtc delete this defines here

2024-01-10 13:20 UTC, gornekich commented
By the way, just we already have #3294 which introduces furi_hal_rtc_timestamp_to_datetime() function. Let's wait when that PR is merged and rework this PR with this function

2024-01-16 06:31 UTC, skotopes commented
Un-draft when ready

2024-02-06 18:54 UTC, hedger approved these changes

2024-02-06 18:55 UTC, gornekich approved these changes

2024-02-06 18:55 UTC, merged