NFC: system dict skip when user dict is skipped fix
flipperdevices/flipperzero-firmware pull request #3356
Opened 2024-01-10 13:09 UTC by Leptopt1los

# Issue
At the moment, when performing a dictionary attack on MF Classic, when you try to skip the user dictionary, the system dictionary is also skipped after it. This bug is not reproduced if you attach the card to the flipper after reading has started, or if you remove it and reapply it while reading with a user dictionary.

The bug is due to the fact that when an NfcCustomEventDictAttackSkip event occurs with the DictAttackStateUserDictInProgress state, instance->nfc_dict_context.is_card_present is false (see line 226 on nfc_scene_mf_classic_dict_attack.c)

##Issue verification:
- Create manually MF Classic 1k 4byte UID dump
- Write it to magic card
- Try to read it
- Skip user dict

System dict will also be skipped

# What's new

The issue described above is fixed

# Verification 

Same as issue verification. After user dict skipping, system dict attack must be started

# Checklist (For Reviewer)

- [ ] PR has description of feature/bug or link to Confluence/Jira task
- [ ] Description contains actions to verify feature/bugfix
- [ ] I've built this code, uploaded it to the device and verified feature/bugfix

2024-01-11 12:17 UTC, gornekich commented
Hello @Leptopt1los 
Thanks for PR. I reproduced the bug but the problem is in different place. `instance->nfc_dict_context.is_card_present` variable should be updated on MFC poller event, but event is not emitted because of incorrect MFC poller state initialization.

Please, consider attached patch. If it works fine for you, please apply this patch to this PR and we will merge it.
[mfc_poller_fix_patch.txt](https://github.com/flipperdevices/flipperzero-firmware/files/13902994/mfc_poller_fix_patch.txt)
Applying patch: `git apply <path_to_patch_file>`

2024-01-11 12:17 UTC, gornekich requested changes
Not completely correct fix

2024-01-12 08:01 UTC, gornekich approved these changes
Thanks

2024-01-12 08:41 UTC, skotopes approved these changes

2024-01-12 08:41 UTC, merged