furi/core/timer: resolve potential use-after-free post deletion
flipperdevices/flipperzero-firmware pull request #3381
Opened 2024-01-18 00:18 UTC by kbembedded

# What's new

While helping investigate #3380, I stumbled upon invalid behavior in `furi_timer_delete()` where it continues to use a timer handle to detect if the timer has been deleted. This loop checking if the timer was running was introduced in #1716.

This behavior is fine for static timers (declared with `xTimerCreateStatic()` and using non-dynamically allocated memory), but is dangerous in situations where the timer is dynamically allocated. The `xTimerDelete()` call is responsible for freeing the timer handle. Due to this, there is always potential for `free()ed` memory to be reallocated and initialized while `furi_timer_free()` is spinning and waiting for the timer to stop which could lead to a crash or deadlock.

This PR addresses that by first safely removing the FURI callback handle from the TimerID of the timer. At this point, if the timer fires, `TimerCallback()` in FURI timers would be called, but with a `NULL`  TimerID nothing further would happen.

Now, the allocated callback memory can be freed without issue. And finally the call to `xTimerDelete()` will submit the timer for deletion in such a way that FURI no longer needs to wait for it to be removed.

# Verification 

Unfortunately, I don't have any application code where this actually causes an issue. This is not an issue I experienced in any real scenario. I only noticed it while doing a deep read of the FURI timer code.

# Checklist (For Reviewer)

- [ ] PR has description of feature/bug or link to Confluence/Jira task
- [ ] Description contains actions to verify feature/bugfix
- [ ] I've built this code, uploaded it to the device and verified feature/bugfix

2024-01-18 07:15 UTC, CookiePLMonster commented on furi/core/timer.c
> +     * to NULL; this is wrapped in a critical secion in vTimerSetTimerID, and
```suggestion
     * to NULL; this is wrapped in a critical section in vTimerSetTimerID, and
```

2024-02-06 23:33 UTC, skotopes requested changes

2024-02-06 23:33 UTC, skotopes commented on furi/core/timer.c
>          free(callb);
vTimerSetTimerID doesn't guarantee that timer thread is not running this callback right now. If it is then there will be condition race where you freed callb memory before it was processed.

2024-02-06 23:33 UTC, skotopes commented on furi/core/timer.c
>          free(callb);
So you still have to ensure that timer stopped before removing callback

2024-02-06 23:49 UTC, kbembedded commented on furi/core/timer.c
>          free(callb);
That is a great point. Looks like the correct way to handle teardown in that case be to stop the timer, wait for it to be no longer active, free the callback memory, and then issue a delete request.

I'll get that updated, do some testing, and push a change to the PR in the next day or so.

2024-02-07 20:08 UTC, closed without merging