NFC: Display unread Mifare Classic bytes as question marks
flipperdevices/flipperzero-firmware pull request #3384
Opened 2024-01-18 22:10 UTC by TollyH

# What's new

- Before, the Mifare Classic data view displayed bytes that hadn't been read from the card as `00`, now they display as `??`

# Verification 

- Open Mifare Classic files in the NFC app that are missing different parts, such as a key, a single block, or an entire sector
- Verify that the bytes are correctly displayed as `??` and line up with the known bytes

# Checklist (For Reviewer)

- [ ] PR has description of feature/bug or link to Confluence/Jira task
- [ ] Description contains actions to verify feature/bugfix
- [ ] I've built this code, uploaded it to the device and verified feature/bugfix

2024-01-23 16:58 UTC, gornekich requested changes
Hello @TollyH ! Thanks for PR!

I like the idea of showing '??' instead of 00, when we didn't read data. I can see small issues in implementation. I think there is a better way to render unknown data.

Please consider my patch attached. You can apply it and check. If everything is fine, please commit this patch, update PR and we will merge it.

To apply patch run `git apply <path_to_patch>`
[mf_classic_render.txt](https://github.com/flipperdevices/flipperzero-firmware/files/14027530/mf_classic_render.txt)

2024-01-23 17:19 UTC, TollyH commented
Thanks @gornekich, I've gone ahead and applied that patch and all seems to working fine

2024-01-23 18:52 UTC, gornekich approved these changes
Thanks!

2024-02-06 17:34 UTC, hedger approved these changes

2024-02-06 17:34 UTC, merged