[FL-3757] NFC: fix application opening from browser
flipperdevices/flipperzero-firmware pull request #3396
Opened 2024-01-25 18:44 UTC by RebornedBrain

# What's new

- Previously when we tried to open .nfc file, where we don't support emulation, from browser then app crashes. Now it will show saved menu

# Verification 

- Go to browser and open any ,nfc file of type which doesn't support emulation. Result: saved menu will be opened.
- Go to browser and open any ,nfc file of type which supports emulation. Result: emulation will be started.

# Checklist (For Reviewer)

- [ ] PR has description of feature/bug or link to Confluence/Jira task
- [ ] Description contains actions to verify feature/bugfix
- [ ] I've built this code, uploaded it to the device and verified feature/bugfix

2024-01-30 11:43 UTC, gornekich submitted a review, later dismissed

2024-01-30 21:08 UTC, xMasterX commented
Hi!
These changes does not fix the issue fully, 
Delete button causes crash
Rename button causes exit into main NFC app - incorrect logic

All required fixes are done in attached patch file, apply before merging
Thanks

[287239.patch](https://github.com/flipperdevices/flipperzero-firmware/files/14104154/287239.patch)

2024-01-31 12:39 UTC, xMasterX commented
And this patch after first one too
[fe05c6.patch](https://github.com/flipperdevices/flipperzero-firmware/files/14111739/fe05c6.patch)

2024-02-05 20:06 UTC, gornekich requested changes
It's more clear all navigation logic is written in one style. Apply patch
[scene_save_success_cleanup.txt](https://github.com/flipperdevices/flipperzero-firmware/files/14171419/scene_save_success_cleanup.txt)

2024-02-05 20:06 UTC, gornekich commented on applications/main/nfc/scenes/nfc_scene_save_success.c
> +                }
Not in the same style as above.

2024-02-06 09:07 UTC, RebornedBrain commented on applications/main/nfc/scenes/nfc_scene_save_success.c
> +                }
Done

2024-02-06 12:52 UTC, gornekich approved these changes

2024-02-06 18:24 UTC, hedger approved these changes

2024-02-06 18:26 UTC, merged