Icons: compression fixes & larger dimension support
flipperdevices/flipperzero-firmware pull request #3564
Opened 2024-04-02 15:16 UTC by hedger

# What's new

- gui: icon API improvements: getters for single frames
- gui: increased max supported dimensions for icons to 65535x65535 (from 255x255)
- gui, compression: unified heatshrink usage, added extra validations for icon decompression results 
- gui, compression: added support for decoding icons larger than decomp buffer size (1k), using dynamic allocations if needed
- unit_tests: reworked to run tests as separate modules from SD card
- fbt: added module filtering for firmware dist package
- loader: api: added md5_calc, bt_keys_storage, pulse_glue, varint

# Verification 

- Everything should work as before
- You can create code that uses large images

# Checklist (For Reviewer)

- [x] PR has description of feature/bug or link to Confluence/Jira task
- [x] Description contains actions to verify feature/bugfix
- [x] I've built this code, uploaded it to the device and verified feature/bugfix

2024-05-13 20:03 UTC, DrZlo13 commented on lib/toolbox/compress.c
> +                encoder, &data_out[res_buff_size], data_out_size - 4 - res_buff_size, &poll_size);
`4`
magic number :(

2024-05-15 13:23 UTC, skotopes requested changes

2024-05-15 13:23 UTC, skotopes commented on applications/services/gui/icon.c
> +    furi_assert(frame < instance->frame_count);
furi_check

2024-05-15 13:23 UTC, skotopes commented on applications/services/gui/icon.h
> + * @return     pointer to XBM bitmap data
Not XBM, flipper compressed XBM

2024-05-15 13:23 UTC, skotopes commented on applications/services/gui/icon.h
> +FURI_DEPRECATED const uint8_t* icon_get_data(const Icon* instance);
Drop maybe? How many apps are actually using it?

2024-05-15 13:23 UTC, skotopes commented on lib/toolbox/compress.c
> +    furi_assert(instance);
furi_check in all public APIs

2024-05-15 13:23 UTC, skotopes commented on lib/toolbox/compress.c
> +    instance->large_decoded_buff = NULL;
Pass advised buffer size and alloc buffer

2024-05-15 13:23 UTC, skotopes commented on lib/toolbox/compress.c
> +        instance->large_decoded_buff = malloc(size_hint);
realloc if needed

2024-05-19 01:57 UTC, Willy-JL commented on applications/services/gui/icon.h
> +FURI_DEPRECATED const uint8_t* icon_get_data(const Icon* instance);
i see its used in loader_applications, for setting js icon when not a fap. also i see Quac! app uses it for similar purpose

2024-05-19 10:28 UTC, skotopes commented on applications/services/gui/icon.h
> +FURI_DEPRECATED const uint8_t* icon_get_data(const Icon* instance);
@Willy-JL We'll keep it for some time.

2024-05-20 17:20 UTC, skotopes approved these changes

2024-05-20 17:23 UTC, merged