[FL-3746] Mifare Plus detection support
flipperdevices/flipperzero-firmware pull request #3607
Opened 2024-04-22 12:10 UTC by Astrrra

# What's new

- Mifare Plus cards are now detected as such and can be partially read and saved

# Verification 

- Read a Mifare Plus card, check that the Type, Size, and Security level are determined correctly

# Checklist (For Reviewer)

- [x] PR has description of feature/bug or link to Confluence/Jira task
- [x] Description contains actions to verify feature/bugfix
- [x] I've built this code, uploaded it to the device and verified feature/bugfix

2024-05-21 09:53 UTC, gornekich requested changes

2024-05-21 09:53 UTC, gornekich commented on lib/nfc/protocols/mf_plus/mf_plus_poller_i.c
> +        }
Do we really need this?

2024-05-21 09:53 UTC, gornekich commented on lib/nfc/protocols/mf_plus/mf_plus_poller.c
> +        detected = mf_plus_poller_read_version(instance, &instance->data->version);
bool = MfPlusError

2024-05-30 13:01 UTC, gornekich submitted a review, later dismissed

2024-06-01 17:07 UTC, skotopes submitted a review, later dismissed

2024-06-10 19:21 UTC, skotopes approved these changes

2024-06-10 19:36 UTC, merged