RPC: Add TarExtract command, some small fixes
flipperdevices/flipperzero-firmware pull request #3685
Opened 2024-06-04 01:36 UTC by Willy-JL

# What's new

- RPC storage command to extract tar file to destination (needs flipperdevices/flipperzero-protobuf#50, probably need to update submodule if/when it is merged)
- Fixed extract failing if not extracting at `/ext` or `/int`, this is because first directory entry in tar is `/` and `path_concat()` would result in `/path/to/dest/` with trailing slash. This is a basic fix but might be worth changing the behavior of the path library in such edge cases?
- Added some missing storage state resets, all other functions had them so it seemed like they should be there, revert if i misunderstood :D

# Verification 

- Storage operations, backup and restore, work fine over RPC
- Tar files (like resources.tar, so USTAR format) can be extracted to chosen destination (not sure on easiest way to make one-off RPC calls to test)

# Checklist (For Reviewer)

- [ ] PR has description of feature/bug or link to Confluence/Jira task
- [ ] Description contains actions to verify feature/bugfix
- [ ] I've built this code, uploaded it to the device and verified feature/bugfix

2024-06-06 15:43 UTC, gsurkov commented
@Willy-JL 
> not sure on easiest way to make one-off RPC calls to test

We have some python scripts for that purpose which can be found [here](https://github.com/flipperdevices/flipperzero_protobuf_py).

In the meantime, I've added support for `TarExtractRequest` at flipperdevices/flipperzero_protobuf_py#25

2024-06-06 17:06 UTC, gsurkov requested changes

2024-06-06 17:06 UTC, gsurkov commented on applications/services/rpc/rpc_storage.c
> +    rpc_system_storage_reset_state(rpc_storage, session, true);
Not needed as the same call has already been made in `rpc_system_storage_list_process()`

2024-06-07 09:53 UTC, gsurkov approved these changes, later dismissed

2024-06-08 13:00 UTC, skotopes approved these changes

2024-06-08 13:15 UTC, merged