CCID: Improve request and response data handling
flipperdevices/flipperzero-firmware pull request #3741
Opened 2024-06-30 23:26 UTC by kidbomb

# What's new

 - Add iso7816_set_response function: serves a helpers to set SW1 and SW2 values
 - improved iso7816_read_response_apdu by correctly parsing Lc and Le values
 - add client script to make testing easier

# Verification 

- Start CCID Test application
- run the client.py script under pplications/debug/ccid_test/client
- Select the 'Generic USB Smart Card Reader'
- All tests should pass

# Checklist (For Reviewer)

- [ ] PR has description of feature/bug or link to Confluence/Jira task
- [ ] Description contains actions to verify feature/bugfix
- [ ] I've built this code, uploaded it to the device and verified feature/bugfix

2024-07-01 12:00 UTC, hedger requested changes, later dismissed
Please run ./fbt format_py

2024-07-01 23:35 UTC, kidbomb commented
> Please run ./fbt format_py

Done!

2024-07-03 12:21 UTC, skotopes requested changes

2024-07-03 12:21 UTC, skotopes commented on applications/debug/ccid_test/iso7816_t0_apdu.h
>  struct ISO7816_Command_APDU {
Normally we do `typedef struct ...`, otherwise you have to repeat yourself

2024-07-03 12:21 UTC, skotopes commented on applications/debug/ccid_test/iso7816_t0_apdu.h
>  struct ISO7816_Command_APDU {
Also it will be nice to match type naming with the rest of the project

2024-07-03 12:21 UTC, skotopes commented on applications/debug/ccid_test/iso7816_t0_apdu.h
> +    uint16_t Lc; //data length
Same goes for struct member names

2024-07-03 12:21 UTC, skotopes commented on targets/furi_hal_include/furi_hal_usb_ccid.h
> +#define CCID_SHORT_APDU_SIZE 0xFF
wrapping defines in () helps to to prevent various template expansion bugs

2024-07-03 12:21 UTC, skotopes commented on applications/debug/ccid_test/iso7816_response.h
> +#ifndef _ISO7816_RESPONSE_H_
normally we use `#pragma once`

2024-07-03 12:44 UTC, skotopes commented
un-draft when ready

2024-07-04 20:31 UTC, kidbomb commented on applications/debug/ccid_test/iso7816_t0_apdu.h
> +    uint16_t Lc; //data length
I am keeling these this way because the struct member names match the ISO7816 standard names

2024-07-06 11:03 UTC, skotopes approved these changes

2024-07-06 11:08 UTC, merged