[FL-3752] HID/BLE Keyboard UI refactoring
flipperdevices/flipperzero-firmware pull request #3777
Opened 2024-07-10 01:38 UTC by Astrrra

# What's new

- See FL-3752

# Verification 

- Verify that the behavior and the visual changes match the ones described in the ticket

# Checklist (For Reviewer)

- [ ] PR has description of feature/bug or link to Confluence/Jira task
- [ ] Description contains actions to verify feature/bugfix
- [ ] I've built this code, uploaded it to the device and verified feature/bugfix

2024-07-11 23:40 UTC, hedger requested changes, later dismissed

2024-07-11 23:40 UTC, hedger commented on applications/system/hid_app/views/hid_keyboard.c
> +        char key_str[2] = "\0\0";
= {key.key, '\0'}

2024-07-11 23:40 UTC, hedger commented on applications/system/hid_app/views/hid_keyboard.c
> +                MARGIN_TOP + y * (KEY_HEIGHT + KEY_PADDING) + KEY_HEIGHT / 2 + 1,
make a single call with optional value (+1/0) depending on if()

2024-07-11 23:40 UTC, hedger commented on applications/system/hid_app/views/hid_keyboard.c
>          canvas_draw_str_aligned(
wrap into a function taking (value, x, y, x_offs, y_offs)

2024-07-16 12:55 UTC, hedger commented
<img width="1291" alt="image" src="https://github.com/user-attachments/assets/a41c5b22-7ff0-427c-9dbb-53757c1d70c7">

1. Lower modifier keys row text is not vertically aligned (1 px) when not pressed
2. Pressed shift key is not aligned
3. `/ \ '` keys not affected by shift

2024-07-17 10:40 UTC, Astrrra commented
@hedger 1 and 2 are intentional (to make buttons look like they're actually pressed down), 3 has been fixed

2024-07-18 07:10 UTC, skotopes approved these changes

2024-07-18 07:13 UTC, merged