[FL-3897] Happy mode
flipperdevices/flipperzero-firmware pull request #3863
Opened 2024-08-30 13:46 UTC by portasynthinca3

# What's new
Added a mode in which the dolphin never gets angry, as requested in #3843. This mode can be toggled via Settings > Desktop > Happy Mode with different screens displayed depending on whether the setting is currently enabled or disabled:
![happy_disabled](https://github.com/user-attachments/assets/621b348b-f36a-4f2d-9f1a-8ce3b176dac7)
![happy_enabled](https://github.com/user-attachments/assets/6113fefc-8742-4bc4-bbf0-2bb4522bf614)

This is implemented by always reporting the internal `butthurt` counter as being at zero when the setting is enabled.

# Verification 
  - Build and flash the firmware with `DOLPHIN_DEBUG` in order to decrease waiting times
  - Wait for the dolphin to get angry
  - Turn on the setting and return to the desktop
  - Verify that the animation is now one of the happy ones
  - Verify that it now says "Mood: Happy" in the passport
  - Turn the setting back off again
  - Verify that the desktop animation is now one of the sad/angry ones
  - Verify that it now says "Mood: Angry" in the passport

# Checklist (For Reviewer)

- [ ] PR has description of feature/bug or link to Confluence/Jira task
- [ ] Description contains actions to verify feature/bugfix
- [ ] I've built this code, uploaded it to the device and verified feature/bugfix

2024-09-05 13:26 UTC, skotopes requested changes

2024-09-05 13:26 UTC, skotopes commented on applications/services/dolphin/dolphin.c
> +DolphinSettings dolphin_get_settings(void) {
DolphinSettings may become heavy with time, I'd use `void dolphin_get_settings(DolphinSettings* settings)` instead of returning it directly.

2024-09-05 13:26 UTC, skotopes commented on applications/services/dolphin/dolphin.c
> +DolphinSettings dolphin_get_settings(void) {
Also it's not our responsibility to acquire Dolphin instance

2024-09-05 13:26 UTC, skotopes commented on applications/settings/desktop_settings/scenes/desktop_settings_scene_happy_mode.c
> +#define SCENE_EXIT_EVENT (0U)
scene local events are bad, there are some places where they still left, but global enum is highly advised

2024-09-05 13:26 UTC, skotopes commented on applications/settings/power_settings_app/scenes/power_settings_scene_power_off.c
> +    DolphinSettings settings = dolphin_get_settings();
exposing DolphinSettings internals is not good. I'd stick with getters and setters

2024-09-05 16:58 UTC, skotopes requested changes

2024-09-05 16:58 UTC, skotopes commented on applications/services/dolphin/helpers/dolphin_state.h
> +    DolphinFlags flags;
enum size is not guaranteed

2024-09-06 16:00 UTC, skotopes requested changes

2024-09-06 16:00 UTC, skotopes commented on applications/services/dolphin/dolphin.c
> +    DolphinEvent event;
missing `furi_check(dolphin);`

all public APIs parameters must be checked

2024-09-06 16:09 UTC, skotopes requested changes

2024-09-06 16:09 UTC, skotopes commented on applications/settings/desktop_settings/desktop_settings_custom_event.h
> +    // reserve 100 for button presses, submenu selections, etc.
input served through another message queue, where this comment came from?

2024-09-07 11:36 UTC, skotopes submitted a review, later dismissed

2024-09-07 11:36 UTC, skotopes commented on applications/settings/desktop_settings/desktop_settings_custom_event.h
> +    // reserve 100 for button presses, submenu selections, etc.
Some other apps directly send events received from views. Because of that they need to reserve enum values at the beginning.

2024-09-07 11:50 UTC, skotopes approved these changes

2024-09-07 11:54 UTC, merged

2024-09-09 06:38 UTC, ivuorinen commented
Thank you ❤️