Replace all calls to strncpy with strlcpy, use strdup more, expose strlcat
flipperdevices/flipperzero-firmware pull request #3866
Opened 2024-09-02 14:58 UTC by CookiePLMonster

# What's new

This PR improves the consistency of string copy calls, removing all uses of `strncpy` and `strcat`, at least from the code that isn't in submodules. `strlcpy` is preferable over `strncpy`, because it doesn't needlessly zero the remaining destination buffer, and it ensures null-termination.

Because `strlcpy` is already used in mjs, I exposed it in the API. Please check if this is fine.

To make buffer sizes consistent, I modifying the following constants to include the space for the null terminator. Please check if this is fine:
* `IBUTTON_KEY_NAME_SIZE`
* `INFRARED_MAX_BUTTON_NAME_LENGTH`
* `INFRARED_MAX_REMOTE_NAME_LENGTH`
* `MAX_TEXT_INPUT_LEN`

# Verification 

* Run a full suite of tests.

# Checklist (For Reviewer)

- [ ] PR has description of feature/bug or link to Confluence/Jira task
- [ ] Description contains actions to verify feature/bugfix
- [ ] I've built this code, uploaded it to the device and verified feature/bugfix

2024-09-06 12:16 UTC, skotopes requested changes

2024-09-06 12:16 UTC, skotopes commented on applications/debug/rpc_debug_app/rpc_debug_app.c
> +            sizeof(app->text_store));
There is one thing that I don't like about sizeof: compiler will not inform you if you change char[] with char*.

2024-09-06 12:16 UTC, skotopes commented
Un-draft when ready

2024-09-06 19:10 UTC, CookiePLMonster commented on applications/debug/rpc_debug_app/rpc_debug_app.c
> +            sizeof(app->text_store));
Fair point. Should I change all the occurrences back? Or does `COUNT_OF` account for it? AFAIK it doesn't.

2024-09-06 19:42 UTC, skotopes commented on applications/debug/rpc_debug_app/rpc_debug_app.c
> +            sizeof(app->text_store));
yep, roll em back please

2024-09-07 16:01 UTC, skotopes approved these changes

2024-09-07 16:16 UTC, merged