Reborned/some api adjustments
flipperdevices/flipperzero-firmware pull request #3918
Opened 2024-09-23 08:27 UTC by RebornedBrain

# What's new

- Added one new function for drawing mirrored xbm bitmaps.
- Now 4a listener throws Halt and FieldOff events to the upper levels

# Verification 

- [ Describe how to verify changes ]

# Checklist (For Reviewer)

- [ ] PR has description of feature/bug or link to Confluence/Jira task
- [ ] Description contains actions to verify feature/bugfix
- [ ] I've built this code, uploaded it to the device and verified feature/bugfix

2024-09-23 18:30 UTC, CookiePLMonster commented
1. Why not simply expose the `IconRotation rotation` argument in `draw_xbm`?
2. It's upside down - is it correct to call it mirrored then? Entering the PR, I expected a draw that would be mirrored horizontally, not rotated 180deg.

2024-09-25 09:39 UTC, RebornedBrain commented
> 1. Why not simply expose the `IconRotation rotation` argument in `draw_xbm`?

It was done in order not to break api backward compatibility.


> 2. It's upside down - is it correct to call it mirrored then? Entering the PR, I expected a draw that would be mirrored horizontally, not rotated 180deg.

If you take a look into `canvas_draw_u8g2_bitmap` which is called under the hood, there will be such code: 
![image](https://github.com/user-attachments/assets/ae44a0a6-c5bb-419d-869b-6c50f74d30e4)
In the switch there is a call to `canvas_draw_u8g2_bitmap_int` which has bool parameter mirror, and this parameter is true in case of `IconRotation180`. Here is the reason why I called this function mirror.

2024-09-30 12:20 UTC, RebornedBrain commented
Also this PR solves the same problem described [here ](https://github.com/flipperdevices/flipperzero-firmware/pull/3744) 
In addition it provides possiblity to send also S-block and R-block

2024-09-30 12:52 UTC, CookiePLMonster commented
> It was done in order not to break api backward compatibility.

You can make `IconRotation0` a default parameter and break ABI, but not sources.

2024-10-14 13:59 UTC, skotopes requested changes

2024-10-14 13:59 UTC, skotopes commented on applications/services/gui/canvas.c
> +void canvas_draw_xbm_custom(
canvas_draw_xbm_ex please

2024-10-14 13:59 UTC, skotopes commented on targets/f7/api_symbols.csv
> +Version,+,77.0,,
f18 too please

2024-10-14 14:00 UTC, CookiePLMonster commented on applications/services/gui/canvas.c
> +void canvas_draw_xbm_custom(
Also it's a nice practice to have the base function call the `_ex`, so refactor `canvas_draw_xbm` to do nothing except call `canvas_draw_xbm_ex` with `IconRotation0`.

2024-10-14 14:02 UTC, skotopes commented on applications/services/gui/canvas.c
> +void canvas_draw_xbm_custom(
yep

2024-10-14 17:17 UTC, skotopes approved these changes

2024-10-14 17:22 UTC, merged