[FL-3917] Add the ability to send a signal once via RPC
flipperdevices/flipperzero-firmware pull request #4000
Opened 2024-11-13 10:54 UTC by Astrrra

# What's new

- New RPC request for sending a signal once

# Verification 

- [ Describe how to verify changes ]

# Checklist (For Reviewer)

- [ ] PR has description of feature/bug or link to Confluence/Jira task
- [ ] Description contains actions to verify feature/bugfix
- [ ] I've built this code, uploaded it to the device and verified feature/bugfix

2024-12-02 09:18 UTC, LionZXY submitted a review, later dismissed

2024-12-13 18:51 UTC, gsurkov requested changes

2024-12-13 18:51 UTC, gsurkov commented on applications/main/infrared/scenes/infrared_scene_rpc.c
> +                scene_manager_stop(infrared->scene_manager);
Lines 169 & 170 are unnecessary, the app should only exit when requested by the mobile companion

2024-12-13 18:51 UTC, gsurkov commented on applications/main/infrared/scenes/infrared_scene_rpc.c
> +                        infrared_tx_start_button_index(infrared, app_state->current_button_index);
There is no guarantee that the signal will be sent only once, as there is a worker being asynchronously spun up only to be stopped right away.
Try using `infrared_signal_transmit` instead (see how it is done in `infrared_brute_force.c`)

2024-12-17 13:03 UTC, gsurkov approved these changes

2024-12-17 13:12 UTC, merged