BadUSB: Mouse control
flipperdevices/flipperzero-firmware pull request #4004
Opened 2024-11-15 23:03 UTC by jetrp1

# BadUSB: Mouse Control

I often found myself automating various functionality and wanting to be able to trigger a mouse click. This PR will add basic mouse functionality to the BadUSB App. Additionally this makes mouse movement more accessible for research on how this type of movement can be used in a security sensitive enviroment.

## What's new

Several new mouse commands:
- LEFTCLICK
- RIGHTCLICK
- MOUSEMOVE
- MOUSE SCROLL

Documentation also updated to reflect the changes

Additionally I implemented functionality for the Middle click (often the mouse wheel button) but in my testing it seemed to only work some of the time. 

## Verification 

I found the easiest way to visualize the mouse movements was to use minecraft as that will show the movements very easily. My script here includes the MIDDLECLICK function, but as you see that does not work yet. If I get some more time int he future I'll look into why that does not work as expected and create an PR for that.

 I used the following BadUSB script:

``` 
REM Testing Mouse Functions

DEFAULT_DELAY 1000

STRING t
STRING LEFTCLICK
ENTER
DELAY 1500
LEFTCLICK

STRING t
STRING RIGHTCLICK
ENTER
DELAY 1500
RIGHTCLICK

STRING t
STRING MIDDLECLICK - has been mapped to select slot 5 on game hotbar
ENTER
DELAY 1500
MIDDLECLICK

STRING t
STRING MOUSESCROLL
ENTER
MOUSESCROLL 1
REPEAT 4
MOUSESCROLL -1
REPEAT 4

STRING t
STRING MOUSE_SCROLL
ENTER
MOUSE_SCROLL 2
MOUSE_SCROLL -2

STRING t
STRING MOUSEMOVE
ENTER 
MOUSEMOVE 50 0
REPEAT 8
MOUSEMOVE 0 50
REPEAT 8
MOUSEMOVE -50 -50
REPEAT 8

STRING t
STRING MOUSE_MOVE
ENTER 
MOUSE_MOVE 50 0
REPEAT 8
MOUSE_MOVE 0 50
REPEAT 8
MOUSE_MOVE -50 -50
REPEAT 8

STRING t
STRING HOLD LEFT_CLICK
ENTER
HOLD LEFT_CLICK
DELAY 5000
RELEASE LEFT_CLICK

MOUSEMOVE 500 -100

STRING t
STRING REPEAT
ENTER
STRING 2
RIGHT_CLICK
REPEAT 3

STRING t
STRING TESTING DONE
ENTER

```
A Short video of running this script:

[https://youtu.be/hi02vP7v6do](https://youtu.be/hi02vP7v6do)

## Checklist (For Reviewer)

- [ ] PR has description of feature/bug or link to Confluence/Jira task
- [ ] Description contains actions to verify feature/bugfix
- [ ] I've built this code, uploaded it to the device and verified feature/bugfix

2024-11-22 02:43 UTC, Willy-JL commented
i wanted to implement something like this for a while and had it on my todo list, happy to see its becoming a reality! great work! :100:

2024-11-24 01:16 UTC, jetrp1 commented
Thank you!

2024-12-23 04:07 UTC, skotopes requested changes

2024-12-23 04:07 UTC, skotopes commented on applications/main/bad_usb/helpers/ducky_script_commands.c
>      uint16_t key = ducky_get_keycode(bad_usb, line, true);
You will get valid key code here (first symbol of argument will become one).

2024-12-23 04:07 UTC, skotopes commented on applications/main/bad_usb/helpers/ducky_script_commands.c
> +    if(isMouse) {
But it will be ignored because of this condition.

2024-12-23 04:07 UTC, skotopes commented on applications/main/bad_usb/helpers/ducky_script_commands.c
> +    key = ducky_get_mouse_keycode_by_name(line);
I understand that badusb code is not the best example, but I got feeling that what you doing here makes it even more difficult to read. 

Do you mind to try to refactor keycode parsing and handling in more explicit way? In a way where if you started mouse branch then you do mouse branch and there is no places where keyboard and mouse collide?

2024-12-23 04:07 UTC, skotopes commented
Un-draft when ready and let me know if you need any help.

2025-01-19 04:48 UTC, jetrp1 commented
I should be able to work on this soon.

2025-02-03 01:20 UTC, jetrp1 commented
The hold and release functions have both been reworked to remove the bug preventing keyboard hold functionality. They should both be much more readable now also. I tried to keep it clear when working on Keyboard vs mouse keys. 
 

[Updated Demo Video](https://youtu.be/dAm6TCgmsD8) 
In the video we do not see the scroll down register since the webpage dosn't have space to scroll. you can also see that the middle click is working. 

<details>
  <summary>Demo Script Used</summary>
  ```
  ID 1234:abcd Generic:USB Keyboard
  REM Declare ourselves as a generic usb keyboard
  REM You can override this to use something else
  REM Check the `lsusb` command to know your own devices IDs
  
  DEFAULT_DELAY 200
  DEFAULT_STRING_DELAY 100
  
  STRING qwertyuiop
  STRING asdfghjkl
  STRING zxcvbnm
  STRING 1234567890
  
  DELAY 1000
  
  REM Test all mouse functions
  LEFTCLICK
  RIGHTCLICK
  MIDDLECLICK
  
  DELAY 1000
  
  MOUSEMOVE -10 0
  REPEAT 20
  MOUSEMOVE 0 10
  REPEAT 20
  MOUSEMOVE 10 0
  REPEAT 20
  MOUSEMOVE 0 -10
  REPEAT 20
  
  DELAY 1000
  
  MOUSESCROLL -50
  MOUSESCROLL 50
  
  DELAY 1000
  
  REM Verify Mouse hold working
  HOLD LEFTCLICK
  DELAY 2000
  RELEASE LEFTCLICK
  
  DELAY 1000
  
  REM Verify KB hold working
  HOLD M
  DELAY 2000
  RELEASE M
  
  ENTER

</details>

[Testing Website](https://shawon9324.github.io/apps/keytester/)

2025-02-03 01:23 UTC, jetrp1 commented on applications/main/bad_usb/helpers/ducky_script_commands.c
> +    if(isMouse) {
updated handling to keep kb hold functionality

2025-02-19 23:23 UTC, skotopes approved these changes

2025-02-19 23:24 UTC, merged