[FL-1690] Archive app: favorites.txt
flipperdevices/flipperzero-firmware pull request #662
Opened 2021-08-20 13:55 UTC by itsyourbedtime

# What's new

- Archive app now using `favorites.txt` instead of key duplication

# Verification 

- Flash, insert sd card
- `favorites.txt` created automatically upon first added key
- Try pinning/unpinning, deletion and renaming of keys 

# Checklist (do not modify)

- [x] PR has description of feature/bug or link to Confluence/Jira task
- [x] Description contains actions to verify feature/bugfix
- [x] I've built this code, uploaded it to the device and verified feature/bugfix

2021-08-20 14:56 UTC, DrZlo13 requested changes

2021-08-20 14:56 UTC, DrZlo13 commented on applications/archive/archive.c
> +static bool archive_favorites_action(
Writing a "superfunction" is bad practice, try to split this into separate functions for each action. 

We also have file_worker in the library, which makes working with files much easier, for example, it has the read_until method that you invented here.

2021-08-20 14:57 UTC, DrZlo13 requested changes

2021-08-20 14:57 UTC, DrZlo13 commented on applications/archive/archive.c
> +    bool result = storage_file_open(file, path, FSAM_WRITE, FSOM_OPEN_APPEND);
Also, use file_worker.

2021-08-28 11:35 UTC, skotopes approved these changes

2021-08-28 11:39 UTC, skotopes approved these changes

2021-08-28 11:43 UTC, DrZlo13 approved these changes

2021-08-28 11:46 UTC, merged