[FL-1946] RPC App launch
flipperdevices/flipperzero-firmware pull request #758
Opened 2021-10-12 23:01 UTC by albkharisov

# What's new

- RPC: support launching applications
- RPC: getting global lock status
- Replace Unit Tests Application with CLI Unit Tests command

# Verification 

- Build with env var "APP_UNIT_TESTS=1" and run tests in CLI (btw, have to disable DEBUG=0 and enable COMPACT=1)
- No way to test Application Start command for now. But it's tested in unit tests

# Checklist (do not modify)

- [x] PR has description of feature/bug or link to Confluence/Jira task
- [x] Description contains actions to verify feature/bugfix
- [x] I've built this code, uploaded it to the device and verified feature/bugfix

2021-10-12 23:51 UTC, DrZlo13 requested changes

2021-10-12 23:51 UTC, DrZlo13 commented on applications/rpc/rpc.c
> +        cnt += ADD_STR(str, cnt, "\tapp_start {\r\n");
use string_t

2021-10-13 13:47 UTC, albkharisov commented on applications/rpc/rpc.c
> +        cnt += ADD_STR(str, cnt, "\tapp_start {\r\n");
Fixed

2021-10-13 15:28 UTC, skotopes approved these changes

2021-10-13 15:38 UTC, DrZlo13 approved these changes

2021-10-13 15:39 UTC, merged