[FL-1955] CLI RPC
flipperdevices/flipperzero-firmware pull request #781
Opened 2021-10-21 17:36 UTC by albkharisov

# What's new

- RPC: added CLI command to start session - all input bytes goes into RPC, all RPC output goes into VCP
- RPC: added command to close session (actually it only notifies transport layer)
- RPC: added recursive rmdir
- RPC: hard-coded listing for root directory (any, ext, int)
- Fixed CLI leak
- Fixed furi_record_delete leak
- Unit tests: repaired
- Unit tests: corrected output - remove excess, change dots with progress spinner
- Unit tests: added leak check
- Unit tests: SD mount check before start

# Verification 

- Run unit_tests
- Run CLI command start_rpc_session and try to send something via protobuf (I can share my ugly python test script for tests)
- Send RPC remove command for non-empty directory. Try with and without recursive flag
- Send RPC list command for root directory

# Checklist (do not modify)

- [x] PR has description of feature/bug or link to Confluence/Jira task
- [x] Description contains actions to verify feature/bugfix
- [x] I've built this code, uploaded it to the device and verified feature/bugfix

2021-10-25 00:29 UTC, skotopes requested changes

2021-10-25 00:29 UTC, skotopes commented on applications/cli/cli_rpc.c
> +
Why is it in cil service?

2021-10-25 00:29 UTC, skotopes commented on applications/cli/cli_commands.c
> +        cli, "start_rpc_session", CliCommandFlagDefault, cli_command_start_rpc_session, NULL);
Why is it here?

2021-10-25 00:29 UTC, skotopes commented on applications/cli/cli_rpc.c
> +
Whole thing is a part of RPC service and must live there.

2021-10-25 00:29 UTC, skotopes commented on applications/cli/cli_rpc.c
> +    while(!exit) {
who is going to set `exit`?

2021-10-25 00:29 UTC, skotopes commented on applications/rpc/rpc.c
> +    string_init(str);
You do understand that you can printf directly without buffer ?

2021-10-25 00:29 UTC, skotopes commented on applications/cli/cli_rpc.c
> +    rpc_set_session_closed_callback(rpc_session, cli_session_closed_callback);
Since you working with rcp_session, change method names to `rpc_session_DO_SOMETHING`

2021-10-25 00:29 UTC, skotopes commented on applications/rpc/rpc.h
> + *      rpc_feed_bytes();
rpc_session_feed()

2021-10-25 00:29 UTC, skotopes commented on applications/rpc/rpc_storage.c
>  static void rpc_system_storage_list_process(const PB_Main* request, void* context) {
what `_process` part means?

2021-10-25 00:29 UTC, skotopes commented on applications/tests/rpc/rpc_test.c
>      test_rpc_storage_list_run("/ext/nfc", ++command_id);
going to fail without sd-card, QA were complaining about it.

2021-10-25 00:29 UTC, skotopes commented on applications/storage/storage-external-api.c
> +    next_dir:
not really happy to see it here

2021-10-25 06:56 UTC, albkharisov commented on applications/rpc/rpc.c
> +    string_init(str);
I don't want my printing to be interrupted, so fill buffer and print it.

2021-10-25 06:58 UTC, albkharisov commented on applications/cli/cli_rpc.c
> +    while(!exit) {
deprecated. I'll delete it.

2021-10-25 07:02 UTC, albkharisov commented on applications/rpc/rpc_storage.c
>  static void rpc_system_storage_list_process(const PB_Main* request, void* context) {
All functions ended with `_process` are entry points for handling certain type of message.
Function `rpc_system_storage_list_root()` is not entry point, it's called from `rpc_system_storage_list_process`

2021-10-25 07:03 UTC, albkharisov commented on applications/storage/storage-external-api.c
> +    next_dir:
Why?

2021-10-25 07:10 UTC, albkharisov commented on applications/tests/rpc/rpc_test.c
>      test_rpc_storage_list_run("/ext/nfc", ++command_id);
Ok, I add SD-card check at start of test running.
I don't think that I should take care of handling SD-card removing in the middle of tests.

2021-10-26 15:54 UTC, skotopes approved these changes

2021-10-26 16:05 UTC, merged