SubGhz: GUI RAW Read view
flipperdevices/flipperzero-firmware pull request #832
Opened 2021-11-19 16:10 UTC by Skorpionm

# What's new

- [ Describe changes here ]

# Verification 

- [ Describe how to verify changes ]

# Checklist (do not modify)

- [ ] PR has description of feature/bug or link to Confluence/Jira task
- [ ] Description contains actions to verify feature/bugfix
- [ ] I've built this code, uploaded it to the device and verified feature/bugfix

2021-11-23 17:20 UTC, skotopes approved these changes

2021-11-23 17:24 UTC, skotopes requested changes

2021-11-23 17:24 UTC, skotopes commented on applications/subghz/views/subghz_read_raw.c
> +        // canvas_draw_line(
remove

2021-11-23 17:24 UTC, skotopes commented on applications/subghz/views/subghz_read_raw.c
> +            //string_reset(model->frequency_str);
remove

2021-11-23 17:45 UTC, Skorpionm commented on applications/subghz/views/subghz_read_raw.c
> +        // canvas_draw_line(
ok

2021-11-23 17:45 UTC, Skorpionm commented on applications/subghz/views/subghz_read_raw.c
> +            //string_reset(model->frequency_str);
ok

2021-11-24 13:59 UTC, skotopes approved these changes

2021-11-24 13:59 UTC, merged