SubGhz: add GFSK modulation, refactoring subghz_chat
flipperdevices/flipperzero-firmware pull request #866
Opened 2021-12-04 15:51 UTC by Skorpionm

# What's new

- [ Describe changes here ]

# Verification 

- [ Describe how to verify changes ]

# Checklist (do not modify)

- [ ] PR has description of feature/bug or link to Confluence/Jira task
- [ ] Description contains actions to verify feature/bugfix
- [ ] I've built this code, uploaded it to the device and verified feature/bugfix

2021-12-04 19:06 UTC, aprosvetova commented on applications/subghz/helpers/subghz_chat.c
> +static void subghz_chat_worker_udate_event_chat(void* context) {
update

2021-12-04 19:39 UTC, Skorpionm commented on applications/subghz/helpers/subghz_chat.c
> +static void subghz_chat_worker_udate_event_chat(void* context) {
+

2021-12-08 09:10 UTC, DrZlo13 requested changes

2021-12-08 09:10 UTC, DrZlo13 commented on applications/subghz/helpers/subghz_chat.h
> +    SubghzChatEvent event;
SubghzChatEventType

2021-12-08 09:10 UTC, DrZlo13 commented on applications/subghz/helpers/subghz_chat.h
> +} SubghzChatQueue;
SubghzChatEvent

2021-12-08 09:10 UTC, DrZlo13 commented on applications/subghz/helpers/subghz_chat.c
> +void subghz_chat_worker_set_event_chat(SubGhzChatWorker* instance, SubghzChatQueue* event) {
subghz_chat_worker_**put**_event_chat

2021-12-08 09:10 UTC, DrZlo13 commented on applications/subghz/helpers/subghz_chat.c
> +    furi_assert(instance);
furi_assert(!instance->worker_running)

2021-12-08 09:10 UTC, DrZlo13 commented on applications/subghz/helpers/subghz_chat.h
> +void subghz_chat_worker_set_event_chat(SubGhzChatWorker* instance, SubghzChatQueue* event);
subghz_chat_worker_**put**_event_chat

2021-12-08 09:10 UTC, DrZlo13 commented on lib/subghz/subghz_tx_rx_worker.c
> +    instance->satus = SubGhzTxRxWorkerStatusTx;
instance->s**t**atus

2021-12-08 12:31 UTC, Skorpionm commented on lib/subghz/subghz_tx_rx_worker.c
> +    instance->satus = SubGhzTxRxWorkerStatusTx;
Ok

2021-12-08 12:31 UTC, Skorpionm commented on applications/subghz/helpers/subghz_chat.h
> +void subghz_chat_worker_set_event_chat(SubGhzChatWorker* instance, SubghzChatQueue* event);
Ok

2021-12-08 12:31 UTC, Skorpionm commented on applications/subghz/helpers/subghz_chat.c
> +    furi_assert(instance);
Ok

2021-12-08 12:31 UTC, Skorpionm commented on applications/subghz/helpers/subghz_chat.c
> +void subghz_chat_worker_set_event_chat(SubGhzChatWorker* instance, SubghzChatQueue* event) {
Ok

2021-12-08 12:32 UTC, Skorpionm commented on applications/subghz/helpers/subghz_chat.h
> +} SubghzChatQueue;
Ok

2021-12-08 12:32 UTC, Skorpionm commented on applications/subghz/helpers/subghz_chat.h
> +    SubghzChatEvent event;
Ok

2021-12-08 13:13 UTC, skotopes approved these changes

2021-12-08 13:41 UTC, DrZlo13 approved these changes

2021-12-08 13:42 UTC, merged