[FL-1958] U2F prototype
flipperdevices/flipperzero-firmware pull request #879
Opened 2021-12-07 17:29 UTC by nminaylov

# What's new

- [ Describe changes here ]

# Verification 

- [ Describe how to verify changes ]

# Checklist (do not modify)

- [ ] PR has description of feature/bug or link to Confluence/Jira task
- [ ] Description contains actions to verify feature/bugfix
- [ ] I've built this code, uploaded it to the device and verified feature/bugfix

2021-12-21 16:49 UTC, skotopes requested changes

2021-12-21 16:49 UTC, skotopes commented on applications/u2f/u2f.c
> +bool u2f_alloc(U2fData** U2F_inst) {
It's better to split it into allocator and initialiser

2021-12-22 10:46 UTC, aprosvetova requested changes, later dismissed

2021-12-22 10:46 UTC, aprosvetova commented on firmware/targets/furi-hal-include/furi-hal-crypto.h
> +bool firi_hal_crypto_verify_key(uint8_t key_slot);
furi

2021-12-22 20:01 UTC, skotopes approved these changes

2021-12-22 20:04 UTC, merged