Add I2C Scanner application
flipperdevices/flipperzero-firmware pull request #898
Opened 2021-12-14 08:14 UTC by okalachev

Hi! I made and tested a graphical I2C scanner app for Flipper.

I guess having such small debugging tools for common embedded things can make Flipper a very useful tool for developers and "hackers". No need to run an RPi with SSH access from a computer to do a quick testing of an I2C device.

For now the tool scans the I2C bus and shows the list of addresses responded:

<img src="https://user-images.githubusercontent.com/1683279/145952481-42418928-2782-47e7-ba8a-1cccd4c6118b.png" width=25%> <img src="https://user-images.githubusercontent.com/1683279/145952498-064c4784-d9c2-41a4-9db5-1b2c68f83439.png" width=25%> <img src="https://user-images.githubusercontent.com/1683279/145952552-8ee7fba5-ba85-43dc-bea4-4f9c06bbc8a4.png" width=25%> 

If you’re ok with such an idea I can add:

* Detecting device types using a database (like https://i2cdevices.org/addresses,  https://github.com/romkey/ESP-Diagnostic-Tool/blob/master/src/i2c_scanner_devices.cpp).
* GUI for reading and writing device registers (with appropriate warnings about possible harm). Basically repeat the functionality of `i2c-tools` for Linux.
* Take out the scanning procedure to a separate thread (now the app is one-threaded for the sake of code simplicity).

# Checklist (do not modify)

- [ ] PR has description of feature/bug or link to Confluence/Jira task
- [ ] Description contains actions to verify feature/bugfix
- [ ] I've built this code, uploaded it to the device and verified feature/bugfix

2021-12-14 13:53 UTC, aprosvetova commented
Looks like this belongs to the GPIO app.

2021-12-15 00:03 UTC, okalachev commented
So, should I transfer this thing into the GPIO app?

2021-12-15 00:08 UTC, DrZlo13 commented
Since we already have the ability to load applications from the SD card, I would prefer that this application remain separate. It doesn't look like basic Flipper functionality.

2021-12-15 00:15 UTC, skotopes requested changes

2021-12-15 00:15 UTC, skotopes commented on applications/debug_tools/i2c_scanner.c
> +    bool device_found[128];
We actually have m-lib for C containers: it got arrays and `string_t` that suites perfectly for this task.

2021-12-15 13:24 UTC, okalachev commented
@DrZlo13, it depends on what Flipper is. If it's only doors opener/rfid/nfc/radio cracker, then maybe. If it's more wide embedded "hacking" tool, then, for me, showing the list of I2C devices connected is a very basic feature, as basic as:

* UART monitor
* USB-UART adapter
* PWM generator (for testing servos, motors...)
* GPIO pins manual control

etc

2021-12-15 18:44 UTC, DrZlo13 commented
@okalachev, I didn't make myself clear enough. The app is definitely useful and deserves to be included in our repository, but for now we are definitely not going to add it to the firmware releases.

Space on the flipper flash is very limited, and we are already experiencing a shortage of it. As soon as it becomes possible to download the application from the SD card, we will add this application to the release.

To summarize, we can accept the pull request, but in order for it to appear in other flippers, they will have to enable this application separately and rebuild the firmware.

2021-12-16 08:48 UTC, okalachev commented
So what should I do?

Set the `APP_I2C_SCANNER` flag to zero and/or transfer the app from debug tools to somewhere else?

By the way, the idea that it should belong to GPIO app does make sense, on my opinion.

2021-12-21 12:46 UTC, okalachev commented
@DrZlo13?

2021-12-21 14:13 UTC, DrZlo13 commented
@okalachev 
Set the APP_I2C_SCANNER flag to zero and make the changes requested by @skotopes.

2022-01-27 16:40 UTC, skotopes commented
This PR is marked as inactive and will be automatically closed in 7 days.

2022-01-27 17:01 UTC, closed without merging