SubGhz: Test
flipperdevices/flipperzero-firmware pull request #969
Opened 2022-01-26 15:49 UTC by Skorpionm

# What's new

- [ Describe changes here ]

# Verification 

- [ Describe how to verify changes ]

# Checklist (do not modify)

- [ ] PR has description of feature/bug or link to Confluence/Jira task
- [ ] Description contains actions to verify feature/bugfix
- [ ] I've built this code, uploaded it to the device and verified feature/bugfix

2022-03-02 19:57 UTC, DrZlo13 requested changes

2022-03-02 19:57 UTC, DrZlo13 commented on applications/subghz/views/subghz_frequency_analyzer.c
> +//#include <lib/subghz/protocols/subghz_protocol_princeton.h>
Do not comment unused code.

2022-03-02 19:57 UTC, DrZlo13 commented on applications/subghz/views/subghz_frequency_analyzer.c
> +    //SubGhzFrequencyAnalyzer* instance = context;
Same

2022-03-02 19:57 UTC, DrZlo13 commented on applications/subghz/views/subghz_read_raw.c
> +//#include <lib/subghz/protocols/subghz_protocol_princeton.h>
Same

2022-03-02 19:57 UTC, DrZlo13 commented on applications/subghz/views/subghz_read_raw.c
>      //if(u_rssi > 34) u_rssi = 34;
And again...

2022-03-02 19:57 UTC, DrZlo13 commented on lib/subghz/blocks/const.c
> +#include "const.h"
Do we really need an empty file?

2022-03-02 19:57 UTC, DrZlo13 commented on lib/subghz/blocks/encoder.h
> +//typedef LevelDuration (*SubGhzProtocolCommonEncoderCallback)(void* context);
And same again, cleanup please.

2022-03-02 19:57 UTC, DrZlo13 commented on lib/subghz/blocks/encoder.c
> +#define TAG "SubGhzBlockEncoder"
Empty?

2022-03-02 19:57 UTC, DrZlo13 commented on lib/subghz/blocks/math.h
> +#define bit_read(value, bit) (((value) >> (bit)) & 0x01)
I propose to move all bitwise operations to common_defines.h

2022-03-02 19:57 UTC, DrZlo13 commented on applications/subghz/views/transmitter.c
> +    // SubGhzViewTransmitter* subghz_transmitter = context;
Again

2022-03-02 19:57 UTC, DrZlo13 commented on applications/subghz/views/transmitter.c
> +    // SubGhzViewTransmitter* subghz_transmitter = context;
And again

2022-03-03 06:13 UTC, DrZlo13 commented on lib/subghz/blocks/math.h
> +#define bit_read(value, bit) (((value) >> (bit)) & 0x01)
I think now isn't time for that.

2022-03-03 06:15 UTC, Skorpionm commented on lib/subghz/blocks/const.c
> +#include "const.h"
This file will be needed later.

2022-03-03 06:15 UTC, Skorpionm commented on lib/subghz/blocks/encoder.c
> +#define TAG "SubGhzBlockEncoder"
This file will be needed later.

2022-03-03 06:16 UTC, DrZlo13 approved these changes

2022-03-03 09:48 UTC, merged